// Devin Desktop 3.10.31, linux-x64: https://windsurf-stable.codeiumdata.com/linux-x64/stable/b98cc43128712ba73c60cca73876f58a710aaa27/Devin-linux-x64-3.10.31.tar.gz
// Archive SHA256 (locally calculated): b3ddf1098c11255354d60a0778d7033989eaed85a37bbd55df90167f42eb5346
// Language server SHA256: aced58234bf6fac9cf5b65d9286e971d697b0a60baaee0a812ff0312dffb88de
// Extracted descriptor set SHA256: 9877811de3bc8055852f94aabd7c7affb3964c30f66c43b0cbcd49753abe211d
// Regenerate: bash scripts/update-devin-proto.sh --version 3.10.31
// Recovered from Desktop, not an official proto source release or a CLI compatibility guarantee.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: exa/api_server_pb/api_server.proto

package api_server_pb

import (
	chat_pb "github.com/caigee-cmd/cli2api/internal/providers/devin/devinpb/chat_pb"
	codeium_common_pb "github.com/caigee-cmd/cli2api/internal/providers/devin/devinpb/codeium_common_pb"
	cortex_pb "github.com/caigee-cmd/cli2api/internal/providers/devin/devinpb/cortex_pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessageRequestType int32

const (
	ChatMessageRequestType_CHAT_MESSAGE_REQUEST_TYPE_UNSPECIFIED         ChatMessageRequestType = 0
	ChatMessageRequestType_CHAT_MESSAGE_REQUEST_TYPE_GENERAL             ChatMessageRequestType = 1
	ChatMessageRequestType_CHAT_MESSAGE_REQUEST_TYPE_CONTEXT_CHECK       ChatMessageRequestType = 2
	ChatMessageRequestType_CHAT_MESSAGE_REQUEST_TYPE_PLAN                ChatMessageRequestType = 3
	ChatMessageRequestType_CHAT_MESSAGE_REQUEST_TYPE_COMMAND             ChatMessageRequestType = 4
	ChatMessageRequestType_CHAT_MESSAGE_REQUEST_TYPE_CASCADE             ChatMessageRequestType = 5
	ChatMessageRequestType_CHAT_MESSAGE_REQUEST_TYPE_EVAL                ChatMessageRequestType = 6
	ChatMessageRequestType_CHAT_MESSAGE_REQUEST_TYPE_WINDSURF_REVIEW     ChatMessageRequestType = 7
	ChatMessageRequestType_CHAT_MESSAGE_REQUEST_TYPE_DEEPWIKI            ChatMessageRequestType = 9
	ChatMessageRequestType_CHAT_MESSAGE_REQUEST_TYPE_DEVSTRAL            ChatMessageRequestType = 10
	ChatMessageRequestType_CHAT_MESSAGE_REQUEST_TYPE_CODEMAP_GENERATION  ChatMessageRequestType = 11
	ChatMessageRequestType_CHAT_MESSAGE_REQUEST_TYPE_CODEMAP_SUGGESTIONS ChatMessageRequestType = 12
	ChatMessageRequestType_CHAT_MESSAGE_REQUEST_TYPE_SMART_FRIEND        ChatMessageRequestType = 13
	ChatMessageRequestType_CHAT_MESSAGE_REQUEST_TYPE_LIFEGUARD           ChatMessageRequestType = 14
	ChatMessageRequestType_CHAT_MESSAGE_REQUEST_TYPE_CHECKPOINT          ChatMessageRequestType = 15
	ChatMessageRequestType_CHAT_MESSAGE_REQUEST_TYPE_AI_GATEWAY          ChatMessageRequestType = 16
)

// Enum value maps for ChatMessageRequestType.
var (
	ChatMessageRequestType_name = map[int32]string{
		0:  "CHAT_MESSAGE_REQUEST_TYPE_UNSPECIFIED",
		1:  "CHAT_MESSAGE_REQUEST_TYPE_GENERAL",
		2:  "CHAT_MESSAGE_REQUEST_TYPE_CONTEXT_CHECK",
		3:  "CHAT_MESSAGE_REQUEST_TYPE_PLAN",
		4:  "CHAT_MESSAGE_REQUEST_TYPE_COMMAND",
		5:  "CHAT_MESSAGE_REQUEST_TYPE_CASCADE",
		6:  "CHAT_MESSAGE_REQUEST_TYPE_EVAL",
		7:  "CHAT_MESSAGE_REQUEST_TYPE_WINDSURF_REVIEW",
		9:  "CHAT_MESSAGE_REQUEST_TYPE_DEEPWIKI",
		10: "CHAT_MESSAGE_REQUEST_TYPE_DEVSTRAL",
		11: "CHAT_MESSAGE_REQUEST_TYPE_CODEMAP_GENERATION",
		12: "CHAT_MESSAGE_REQUEST_TYPE_CODEMAP_SUGGESTIONS",
		13: "CHAT_MESSAGE_REQUEST_TYPE_SMART_FRIEND",
		14: "CHAT_MESSAGE_REQUEST_TYPE_LIFEGUARD",
		15: "CHAT_MESSAGE_REQUEST_TYPE_CHECKPOINT",
		16: "CHAT_MESSAGE_REQUEST_TYPE_AI_GATEWAY",
	}
	ChatMessageRequestType_value = map[string]int32{
		"CHAT_MESSAGE_REQUEST_TYPE_UNSPECIFIED":         0,
		"CHAT_MESSAGE_REQUEST_TYPE_GENERAL":             1,
		"CHAT_MESSAGE_REQUEST_TYPE_CONTEXT_CHECK":       2,
		"CHAT_MESSAGE_REQUEST_TYPE_PLAN":                3,
		"CHAT_MESSAGE_REQUEST_TYPE_COMMAND":             4,
		"CHAT_MESSAGE_REQUEST_TYPE_CASCADE":             5,
		"CHAT_MESSAGE_REQUEST_TYPE_EVAL":                6,
		"CHAT_MESSAGE_REQUEST_TYPE_WINDSURF_REVIEW":     7,
		"CHAT_MESSAGE_REQUEST_TYPE_DEEPWIKI":            9,
		"CHAT_MESSAGE_REQUEST_TYPE_DEVSTRAL":            10,
		"CHAT_MESSAGE_REQUEST_TYPE_CODEMAP_GENERATION":  11,
		"CHAT_MESSAGE_REQUEST_TYPE_CODEMAP_SUGGESTIONS": 12,
		"CHAT_MESSAGE_REQUEST_TYPE_SMART_FRIEND":        13,
		"CHAT_MESSAGE_REQUEST_TYPE_LIFEGUARD":           14,
		"CHAT_MESSAGE_REQUEST_TYPE_CHECKPOINT":          15,
		"CHAT_MESSAGE_REQUEST_TYPE_AI_GATEWAY":          16,
	}
)

func (x ChatMessageRequestType) Enum() *ChatMessageRequestType {
	p := new(ChatMessageRequestType)
	*p = x
	return p
}

func (x ChatMessageRequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatMessageRequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_exa_api_server_pb_api_server_proto_enumTypes[0].Descriptor()
}

func (ChatMessageRequestType) Type() protoreflect.EnumType {
	return &file_exa_api_server_pb_api_server_proto_enumTypes[0]
}

func (x ChatMessageRequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatMessageRequestType.Descriptor instead.
func (ChatMessageRequestType) EnumDescriptor() ([]byte, []int) {
	return file_exa_api_server_pb_api_server_proto_rawDescGZIP(), []int{0}
}

type GetChatMessageRequest struct {
	state                protoimpl.MessageState       `protogen:"open.v1"`
	Metadata             *codeium_common_pb.Metadata  `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Prompt               string                       `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ChatMessagePrompts   []*chat_pb.ChatMessagePrompt `protobuf:"bytes,3,rep,name=chat_message_prompts,json=chatMessagePrompts,proto3" json:"chat_message_prompts,omitempty"`
	UseInternalChatModel bool                         `protobuf:"varint,5,opt,name=use_internal_chat_model,json=useInternalChatModel,proto3" json:"use_internal_chat_model,omitempty"`
	// Deprecated: Marked as deprecated in exa/api_server_pb/api_server.proto.
	InternalChatModel        codeium_common_pb.Model                     `protobuf:"varint,6,opt,name=internal_chat_model,json=internalChatModel,proto3,enum=exa.codeium_common_pb.Model" json:"internal_chat_model,omitempty"`
	ChatModelUid             string                                      `protobuf:"bytes,21,opt,name=chat_model_uid,json=chatModelUid,proto3" json:"chat_model_uid,omitempty"`
	RequestType              ChatMessageRequestType                      `protobuf:"varint,7,opt,name=request_type,json=requestType,proto3,enum=exa.api_server_pb.ChatMessageRequestType" json:"request_type,omitempty"`
	Configuration            *codeium_common_pb.CompletionConfiguration  `protobuf:"bytes,8,opt,name=configuration,proto3" json:"configuration,omitempty"`
	ExperimentConfig         *codeium_common_pb.ExperimentConfig         `protobuf:"bytes,9,opt,name=experiment_config,json=experimentConfig,proto3" json:"experiment_config,omitempty"`
	Tools                    []*chat_pb.ChatToolDefinition               `protobuf:"bytes,10,rep,name=tools,proto3" json:"tools,omitempty"`
	DisableParallelToolCalls bool                                        `protobuf:"varint,11,opt,name=disable_parallel_tool_calls,json=disableParallelToolCalls,proto3" json:"disable_parallel_tool_calls,omitempty"`
	ToolChoice               *chat_pb.ChatToolChoice                     `protobuf:"bytes,12,opt,name=tool_choice,json=toolChoice,proto3" json:"tool_choice,omitempty"`
	SystemPromptCacheOptions *chat_pb.PromptCacheOptions                 `protobuf:"bytes,13,opt,name=system_prompt_cache_options,json=systemPromptCacheOptions,proto3" json:"system_prompt_cache_options,omitempty"`
	ChatModelName            string                                      `protobuf:"bytes,14,opt,name=chat_model_name,json=chatModelName,proto3" json:"chat_model_name,omitempty"`
	TrajectoryReference      *cortex_pb.CortexTrajectoryReference        `protobuf:"bytes,15,opt,name=trajectory_reference,json=trajectoryReference,proto3" json:"trajectory_reference,omitempty"`
	CascadeId                string                                      `protobuf:"bytes,16,opt,name=cascade_id,json=cascadeId,proto3" json:"cascade_id,omitempty"`
	PromptId                 string                                      `protobuf:"bytes,17,opt,name=prompt_id,json=promptId,proto3" json:"prompt_id,omitempty"`
	ProviderSource           codeium_common_pb.ProviderSource            `protobuf:"varint,18,opt,name=provider_source,json=providerSource,proto3,enum=exa.codeium_common_pb.ProviderSource" json:"provider_source,omitempty"`
	Language                 codeium_common_pb.Language                  `protobuf:"varint,19,opt,name=language,proto3,enum=exa.codeium_common_pb.Language" json:"language,omitempty"`
	PlannerMode              codeium_common_pb.ConversationalPlannerMode `protobuf:"varint,20,opt,name=planner_mode,json=plannerMode,proto3,enum=exa.codeium_common_pb.ConversationalPlannerMode" json:"planner_mode,omitempty"`
	ExecutionId              string                                      `protobuf:"bytes,22,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	ArenaConvergeCount       *int32                                      `protobuf:"varint,24,opt,name=arena_converge_count,json=arenaConvergeCount,proto3,oneof" json:"arena_converge_count,omitempty"`
	ArenaAssignmentJwt       *string                                     `protobuf:"bytes,25,opt,name=arena_assignment_jwt,json=arenaAssignmentJwt,proto3,oneof" json:"arena_assignment_jwt,omitempty"`
	ModelAssignmentJwt       *string                                     `protobuf:"bytes,26,opt,name=model_assignment_jwt,json=modelAssignmentJwt,proto3,oneof" json:"model_assignment_jwt,omitempty"`
	PromptCacheKey           string                                      `protobuf:"bytes,27,opt,name=prompt_cache_key,json=promptCacheKey,proto3" json:"prompt_cache_key,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GetChatMessageRequest) Reset() {
	*x = GetChatMessageRequest{}
	mi := &file_exa_api_server_pb_api_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMessageRequest) ProtoMessage() {}

func (x *GetChatMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exa_api_server_pb_api_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMessageRequest.ProtoReflect.Descriptor instead.
func (*GetChatMessageRequest) Descriptor() ([]byte, []int) {
	return file_exa_api_server_pb_api_server_proto_rawDescGZIP(), []int{0}
}

func (x *GetChatMessageRequest) GetMetadata() *codeium_common_pb.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetChatMessageRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GetChatMessageRequest) GetChatMessagePrompts() []*chat_pb.ChatMessagePrompt {
	if x != nil {
		return x.ChatMessagePrompts
	}
	return nil
}

func (x *GetChatMessageRequest) GetUseInternalChatModel() bool {
	if x != nil {
		return x.UseInternalChatModel
	}
	return false
}

// Deprecated: Marked as deprecated in exa/api_server_pb/api_server.proto.
func (x *GetChatMessageRequest) GetInternalChatModel() codeium_common_pb.Model {
	if x != nil {
		return x.InternalChatModel
	}
	return codeium_common_pb.Model(0)
}

func (x *GetChatMessageRequest) GetChatModelUid() string {
	if x != nil {
		return x.ChatModelUid
	}
	return ""
}

func (x *GetChatMessageRequest) GetRequestType() ChatMessageRequestType {
	if x != nil {
		return x.RequestType
	}
	return ChatMessageRequestType_CHAT_MESSAGE_REQUEST_TYPE_UNSPECIFIED
}

func (x *GetChatMessageRequest) GetConfiguration() *codeium_common_pb.CompletionConfiguration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *GetChatMessageRequest) GetExperimentConfig() *codeium_common_pb.ExperimentConfig {
	if x != nil {
		return x.ExperimentConfig
	}
	return nil
}

func (x *GetChatMessageRequest) GetTools() []*chat_pb.ChatToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *GetChatMessageRequest) GetDisableParallelToolCalls() bool {
	if x != nil {
		return x.DisableParallelToolCalls
	}
	return false
}

func (x *GetChatMessageRequest) GetToolChoice() *chat_pb.ChatToolChoice {
	if x != nil {
		return x.ToolChoice
	}
	return nil
}

func (x *GetChatMessageRequest) GetSystemPromptCacheOptions() *chat_pb.PromptCacheOptions {
	if x != nil {
		return x.SystemPromptCacheOptions
	}
	return nil
}

func (x *GetChatMessageRequest) GetChatModelName() string {
	if x != nil {
		return x.ChatModelName
	}
	return ""
}

func (x *GetChatMessageRequest) GetTrajectoryReference() *cortex_pb.CortexTrajectoryReference {
	if x != nil {
		return x.TrajectoryReference
	}
	return nil
}

func (x *GetChatMessageRequest) GetCascadeId() string {
	if x != nil {
		return x.CascadeId
	}
	return ""
}

func (x *GetChatMessageRequest) GetPromptId() string {
	if x != nil {
		return x.PromptId
	}
	return ""
}

func (x *GetChatMessageRequest) GetProviderSource() codeium_common_pb.ProviderSource {
	if x != nil {
		return x.ProviderSource
	}
	return codeium_common_pb.ProviderSource(0)
}

func (x *GetChatMessageRequest) GetLanguage() codeium_common_pb.Language {
	if x != nil {
		return x.Language
	}
	return codeium_common_pb.Language(0)
}

func (x *GetChatMessageRequest) GetPlannerMode() codeium_common_pb.ConversationalPlannerMode {
	if x != nil {
		return x.PlannerMode
	}
	return codeium_common_pb.ConversationalPlannerMode(0)
}

func (x *GetChatMessageRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *GetChatMessageRequest) GetArenaConvergeCount() int32 {
	if x != nil && x.ArenaConvergeCount != nil {
		return *x.ArenaConvergeCount
	}
	return 0
}

func (x *GetChatMessageRequest) GetArenaAssignmentJwt() string {
	if x != nil && x.ArenaAssignmentJwt != nil {
		return *x.ArenaAssignmentJwt
	}
	return ""
}

func (x *GetChatMessageRequest) GetModelAssignmentJwt() string {
	if x != nil && x.ModelAssignmentJwt != nil {
		return *x.ModelAssignmentJwt
	}
	return ""
}

func (x *GetChatMessageRequest) GetPromptCacheKey() string {
	if x != nil {
		return x.PromptCacheKey
	}
	return ""
}

type GetChatMessageResponse struct {
	state             protoimpl.MessageState               `protogen:"open.v1"`
	MessageId         string                               `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Timestamp         *timestamppb.Timestamp               `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DeltaText         string                               `protobuf:"bytes,3,opt,name=delta_text,json=deltaText,proto3" json:"delta_text,omitempty"`
	DeltaTokens       uint32                               `protobuf:"varint,4,opt,name=delta_tokens,json=deltaTokens,proto3" json:"delta_tokens,omitempty"`
	StopReason        codeium_common_pb.StopReason         `protobuf:"varint,5,opt,name=stop_reason,json=stopReason,proto3,enum=exa.codeium_common_pb.StopReason" json:"stop_reason,omitempty"`
	DeltaToolCalls    []*codeium_common_pb.ChatToolCall    `protobuf:"bytes,6,rep,name=delta_tool_calls,json=deltaToolCalls,proto3" json:"delta_tool_calls,omitempty"`
	Usage             *codeium_common_pb.ModelUsageStats   `protobuf:"bytes,7,opt,name=usage,proto3" json:"usage,omitempty"`
	CreditCost        int32                                `protobuf:"varint,14,opt,name=credit_cost,json=creditCost,proto3" json:"credit_cost,omitempty"`
	Redact            bool                                 `protobuf:"varint,8,opt,name=redact,proto3" json:"redact,omitempty"`
	DeltaThinking     string                               `protobuf:"bytes,9,opt,name=delta_thinking,json=deltaThinking,proto3" json:"delta_thinking,omitempty"`
	DeltaSignature    string                               `protobuf:"bytes,10,opt,name=delta_signature,json=deltaSignature,proto3" json:"delta_signature,omitempty"`
	ThinkingRedacted  bool                                 `protobuf:"varint,11,opt,name=thinking_redacted,json=thinkingRedacted,proto3" json:"thinking_redacted,omitempty"`
	Latency           float64                              `protobuf:"fixed64,12,opt,name=latency,proto3" json:"latency,omitempty"`
	CompletionProfile *codeium_common_pb.CompletionProfile `protobuf:"bytes,13,opt,name=completion_profile,json=completionProfile,proto3" json:"completion_profile,omitempty"`
	OutputId          string                               `protobuf:"bytes,15,opt,name=output_id,json=outputId,proto3" json:"output_id,omitempty"`
	// Deprecated: Marked as deprecated in exa/api_server_pb/api_server.proto.
	ThinkingId          string `protobuf:"bytes,16,opt,name=thinking_id,json=thinkingId,proto3" json:"thinking_id,omitempty"`
	RequestId           string `protobuf:"bytes,17,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CommittedCreditCost int32  `protobuf:"varint,18,opt,name=committed_credit_cost,json=committedCreditCost,proto3" json:"committed_credit_cost,omitempty"`
	Prompt              string `protobuf:"bytes,19,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Deprecated: Marked as deprecated in exa/api_server_pb/api_server.proto.
	GeminiThoughtSignature        []byte                                      `protobuf:"bytes,20,opt,name=gemini_thought_signature,json=geminiThoughtSignature,proto3" json:"gemini_thought_signature,omitempty"`
	DeltaSignatureType            string                                      `protobuf:"bytes,21,opt,name=delta_signature_type,json=deltaSignatureType,proto3" json:"delta_signature_type,omitempty"`
	CommittedAcuCost              float64                                     `protobuf:"fixed64,22,opt,name=committed_acu_cost,json=committedAcuCost,proto3" json:"committed_acu_cost,omitempty"`
	ActualModelUid                *string                                     `protobuf:"bytes,23,opt,name=actual_model_uid,json=actualModelUid,proto3,oneof" json:"actual_model_uid,omitempty"`
	ArenaInvocationCapReached     bool                                        `protobuf:"varint,24,opt,name=arena_invocation_cap_reached,json=arenaInvocationCapReached,proto3" json:"arena_invocation_cap_reached,omitempty"`
	Phase                         string                                      `protobuf:"bytes,25,opt,name=phase,proto3" json:"phase,omitempty"`
	CommittedQuotaCostBasisPoints *int64                                      `protobuf:"varint,26,opt,name=committed_quota_cost_basis_points,json=committedQuotaCostBasisPoints,proto3,oneof" json:"committed_quota_cost_basis_points,omitempty"`
	CommittedOverageCostCents     *int64                                      `protobuf:"varint,27,opt,name=committed_overage_cost_cents,json=committedOverageCostCents,proto3,oneof" json:"committed_overage_cost_cents,omitempty"`
	ResponseDimensionGroups       []*codeium_common_pb.ResponseDimensionGroup `protobuf:"bytes,28,rep,name=response_dimension_groups,json=responseDimensionGroups,proto3" json:"response_dimension_groups,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *GetChatMessageResponse) Reset() {
	*x = GetChatMessageResponse{}
	mi := &file_exa_api_server_pb_api_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMessageResponse) ProtoMessage() {}

func (x *GetChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exa_api_server_pb_api_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMessageResponse.ProtoReflect.Descriptor instead.
func (*GetChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_exa_api_server_pb_api_server_proto_rawDescGZIP(), []int{1}
}

func (x *GetChatMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GetChatMessageResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GetChatMessageResponse) GetDeltaText() string {
	if x != nil {
		return x.DeltaText
	}
	return ""
}

func (x *GetChatMessageResponse) GetDeltaTokens() uint32 {
	if x != nil {
		return x.DeltaTokens
	}
	return 0
}

func (x *GetChatMessageResponse) GetStopReason() codeium_common_pb.StopReason {
	if x != nil {
		return x.StopReason
	}
	return codeium_common_pb.StopReason(0)
}

func (x *GetChatMessageResponse) GetDeltaToolCalls() []*codeium_common_pb.ChatToolCall {
	if x != nil {
		return x.DeltaToolCalls
	}
	return nil
}

func (x *GetChatMessageResponse) GetUsage() *codeium_common_pb.ModelUsageStats {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *GetChatMessageResponse) GetCreditCost() int32 {
	if x != nil {
		return x.CreditCost
	}
	return 0
}

func (x *GetChatMessageResponse) GetRedact() bool {
	if x != nil {
		return x.Redact
	}
	return false
}

func (x *GetChatMessageResponse) GetDeltaThinking() string {
	if x != nil {
		return x.DeltaThinking
	}
	return ""
}

func (x *GetChatMessageResponse) GetDeltaSignature() string {
	if x != nil {
		return x.DeltaSignature
	}
	return ""
}

func (x *GetChatMessageResponse) GetThinkingRedacted() bool {
	if x != nil {
		return x.ThinkingRedacted
	}
	return false
}

func (x *GetChatMessageResponse) GetLatency() float64 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *GetChatMessageResponse) GetCompletionProfile() *codeium_common_pb.CompletionProfile {
	if x != nil {
		return x.CompletionProfile
	}
	return nil
}

func (x *GetChatMessageResponse) GetOutputId() string {
	if x != nil {
		return x.OutputId
	}
	return ""
}

// Deprecated: Marked as deprecated in exa/api_server_pb/api_server.proto.
func (x *GetChatMessageResponse) GetThinkingId() string {
	if x != nil {
		return x.ThinkingId
	}
	return ""
}

func (x *GetChatMessageResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetChatMessageResponse) GetCommittedCreditCost() int32 {
	if x != nil {
		return x.CommittedCreditCost
	}
	return 0
}

func (x *GetChatMessageResponse) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

// Deprecated: Marked as deprecated in exa/api_server_pb/api_server.proto.
func (x *GetChatMessageResponse) GetGeminiThoughtSignature() []byte {
	if x != nil {
		return x.GeminiThoughtSignature
	}
	return nil
}

func (x *GetChatMessageResponse) GetDeltaSignatureType() string {
	if x != nil {
		return x.DeltaSignatureType
	}
	return ""
}

func (x *GetChatMessageResponse) GetCommittedAcuCost() float64 {
	if x != nil {
		return x.CommittedAcuCost
	}
	return 0
}

func (x *GetChatMessageResponse) GetActualModelUid() string {
	if x != nil && x.ActualModelUid != nil {
		return *x.ActualModelUid
	}
	return ""
}

func (x *GetChatMessageResponse) GetArenaInvocationCapReached() bool {
	if x != nil {
		return x.ArenaInvocationCapReached
	}
	return false
}

func (x *GetChatMessageResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *GetChatMessageResponse) GetCommittedQuotaCostBasisPoints() int64 {
	if x != nil && x.CommittedQuotaCostBasisPoints != nil {
		return *x.CommittedQuotaCostBasisPoints
	}
	return 0
}

func (x *GetChatMessageResponse) GetCommittedOverageCostCents() int64 {
	if x != nil && x.CommittedOverageCostCents != nil {
		return *x.CommittedOverageCostCents
	}
	return 0
}

func (x *GetChatMessageResponse) GetResponseDimensionGroups() []*codeium_common_pb.ResponseDimensionGroup {
	if x != nil {
		return x.ResponseDimensionGroups
	}
	return nil
}

var File_exa_api_server_pb_api_server_proto protoreflect.FileDescriptor

const file_exa_api_server_pb_api_server_proto_rawDesc = "" +
	"\n" +
	"\"exa/api_server_pb/api_server.proto\x12\x11exa.api_server_pb\x1a\x16exa/chat_pb/chat.proto\x1a*exa/codeium_common_pb/codeium_common.proto\x1a\x1aexa/cortex_pb/cortex.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\r\n" +
	"\x15GetChatMessageRequest\x12C\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.exa.codeium_common_pb.MetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12Z\n" +
	"\x14chat_message_prompts\x18\x03 \x03(\v2\x1e.exa.chat_pb.ChatMessagePromptB\b\xbaH\x05\x92\x01\x02\b\x01R\x12chatMessagePrompts\x125\n" +
	"\x17use_internal_chat_model\x18\x05 \x01(\bR\x14useInternalChatModel\x12P\n" +
	"\x13internal_chat_model\x18\x06 \x01(\x0e2\x1c.exa.codeium_common_pb.ModelB\x02\x18\x01R\x11internalChatModel\x12$\n" +
	"\x0echat_model_uid\x18\x15 \x01(\tR\fchatModelUid\x12L\n" +
	"\frequest_type\x18\a \x01(\x0e2).exa.api_server_pb.ChatMessageRequestTypeR\vrequestType\x12T\n" +
	"\rconfiguration\x18\b \x01(\v2..exa.codeium_common_pb.CompletionConfigurationR\rconfiguration\x12T\n" +
	"\x11experiment_config\x18\t \x01(\v2'.exa.codeium_common_pb.ExperimentConfigR\x10experimentConfig\x125\n" +
	"\x05tools\x18\n" +
	" \x03(\v2\x1f.exa.chat_pb.ChatToolDefinitionR\x05tools\x12=\n" +
	"\x1bdisable_parallel_tool_calls\x18\v \x01(\bR\x18disableParallelToolCalls\x12<\n" +
	"\vtool_choice\x18\f \x01(\v2\x1b.exa.chat_pb.ChatToolChoiceR\n" +
	"toolChoice\x12^\n" +
	"\x1bsystem_prompt_cache_options\x18\r \x01(\v2\x1f.exa.chat_pb.PromptCacheOptionsR\x18systemPromptCacheOptions\x12&\n" +
	"\x0fchat_model_name\x18\x0e \x01(\tR\rchatModelName\x12[\n" +
	"\x14trajectory_reference\x18\x0f \x01(\v2(.exa.cortex_pb.CortexTrajectoryReferenceR\x13trajectoryReference\x12\x1d\n" +
	"\n" +
	"cascade_id\x18\x10 \x01(\tR\tcascadeId\x12\x1b\n" +
	"\tprompt_id\x18\x11 \x01(\tR\bpromptId\x12N\n" +
	"\x0fprovider_source\x18\x12 \x01(\x0e2%.exa.codeium_common_pb.ProviderSourceR\x0eproviderSource\x12;\n" +
	"\blanguage\x18\x13 \x01(\x0e2\x1f.exa.codeium_common_pb.LanguageR\blanguage\x12S\n" +
	"\fplanner_mode\x18\x14 \x01(\x0e20.exa.codeium_common_pb.ConversationalPlannerModeR\vplannerMode\x12!\n" +
	"\fexecution_id\x18\x16 \x01(\tR\vexecutionId\x125\n" +
	"\x14arena_converge_count\x18\x18 \x01(\x05H\x00R\x12arenaConvergeCount\x88\x01\x01\x125\n" +
	"\x14arena_assignment_jwt\x18\x19 \x01(\tH\x01R\x12arenaAssignmentJwt\x88\x01\x01\x125\n" +
	"\x14model_assignment_jwt\x18\x1a \x01(\tH\x02R\x12modelAssignmentJwt\x88\x01\x01\x12(\n" +
	"\x10prompt_cache_key\x18\x1b \x01(\tR\x0epromptCacheKeyB\x17\n" +
	"\x15_arena_converge_countB\x17\n" +
	"\x15_arena_assignment_jwtB\x17\n" +
	"\x15_model_assignment_jwtJ\x04\b\x17\x10\x18J\x04\b\x04\x10\x05R\n" +
	"arena_tierR\n" +
	"model_name\"\xeb\v\n" +
	"\x16GetChatMessageResponse\x12&\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tmessageId\x12@\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\ttimestamp\x12\x1d\n" +
	"\n" +
	"delta_text\x18\x03 \x01(\tR\tdeltaText\x12!\n" +
	"\fdelta_tokens\x18\x04 \x01(\rR\vdeltaTokens\x12B\n" +
	"\vstop_reason\x18\x05 \x01(\x0e2!.exa.codeium_common_pb.StopReasonR\n" +
	"stopReason\x12M\n" +
	"\x10delta_tool_calls\x18\x06 \x03(\v2#.exa.codeium_common_pb.ChatToolCallR\x0edeltaToolCalls\x12<\n" +
	"\x05usage\x18\a \x01(\v2&.exa.codeium_common_pb.ModelUsageStatsR\x05usage\x12\x1f\n" +
	"\vcredit_cost\x18\x0e \x01(\x05R\n" +
	"creditCost\x12\x16\n" +
	"\x06redact\x18\b \x01(\bR\x06redact\x12%\n" +
	"\x0edelta_thinking\x18\t \x01(\tR\rdeltaThinking\x12'\n" +
	"\x0fdelta_signature\x18\n" +
	" \x01(\tR\x0edeltaSignature\x12+\n" +
	"\x11thinking_redacted\x18\v \x01(\bR\x10thinkingRedacted\x12\x18\n" +
	"\alatency\x18\f \x01(\x01R\alatency\x12W\n" +
	"\x12completion_profile\x18\r \x01(\v2(.exa.codeium_common_pb.CompletionProfileR\x11completionProfile\x12\x1b\n" +
	"\toutput_id\x18\x0f \x01(\tR\boutputId\x12#\n" +
	"\vthinking_id\x18\x10 \x01(\tB\x02\x18\x01R\n" +
	"thinkingId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x11 \x01(\tR\trequestId\x122\n" +
	"\x15committed_credit_cost\x18\x12 \x01(\x05R\x13committedCreditCost\x12\x16\n" +
	"\x06prompt\x18\x13 \x01(\tR\x06prompt\x12<\n" +
	"\x18gemini_thought_signature\x18\x14 \x01(\fB\x02\x18\x01R\x16geminiThoughtSignature\x120\n" +
	"\x14delta_signature_type\x18\x15 \x01(\tR\x12deltaSignatureType\x12,\n" +
	"\x12committed_acu_cost\x18\x16 \x01(\x01R\x10committedAcuCost\x12-\n" +
	"\x10actual_model_uid\x18\x17 \x01(\tH\x00R\x0eactualModelUid\x88\x01\x01\x12?\n" +
	"\x1carena_invocation_cap_reached\x18\x18 \x01(\bR\x19arenaInvocationCapReached\x12\x14\n" +
	"\x05phase\x18\x19 \x01(\tR\x05phase\x12M\n" +
	"!committed_quota_cost_basis_points\x18\x1a \x01(\x03H\x01R\x1dcommittedQuotaCostBasisPoints\x88\x01\x01\x12D\n" +
	"\x1ccommitted_overage_cost_cents\x18\x1b \x01(\x03H\x02R\x19committedOverageCostCents\x88\x01\x01\x12i\n" +
	"\x19response_dimension_groups\x18\x1c \x03(\v2-.exa.codeium_common_pb.ResponseDimensionGroupR\x17responseDimensionGroupsB\x13\n" +
	"\x11_actual_model_uidB$\n" +
	"\"_committed_quota_cost_basis_pointsB\x1f\n" +
	"\x1d_committed_overage_cost_cents*\xec\x05\n" +
	"\x16ChatMessageRequestType\x12)\n" +
	"%CHAT_MESSAGE_REQUEST_TYPE_UNSPECIFIED\x10\x00\x12%\n" +
	"!CHAT_MESSAGE_REQUEST_TYPE_GENERAL\x10\x01\x12+\n" +
	"'CHAT_MESSAGE_REQUEST_TYPE_CONTEXT_CHECK\x10\x02\x12\"\n" +
	"\x1eCHAT_MESSAGE_REQUEST_TYPE_PLAN\x10\x03\x12%\n" +
	"!CHAT_MESSAGE_REQUEST_TYPE_COMMAND\x10\x04\x12%\n" +
	"!CHAT_MESSAGE_REQUEST_TYPE_CASCADE\x10\x05\x12\"\n" +
	"\x1eCHAT_MESSAGE_REQUEST_TYPE_EVAL\x10\x06\x12-\n" +
	")CHAT_MESSAGE_REQUEST_TYPE_WINDSURF_REVIEW\x10\a\x12&\n" +
	"\"CHAT_MESSAGE_REQUEST_TYPE_DEEPWIKI\x10\t\x12&\n" +
	"\"CHAT_MESSAGE_REQUEST_TYPE_DEVSTRAL\x10\n" +
	"\x120\n" +
	",CHAT_MESSAGE_REQUEST_TYPE_CODEMAP_GENERATION\x10\v\x121\n" +
	"-CHAT_MESSAGE_REQUEST_TYPE_CODEMAP_SUGGESTIONS\x10\f\x12*\n" +
	"&CHAT_MESSAGE_REQUEST_TYPE_SMART_FRIEND\x10\r\x12'\n" +
	"#CHAT_MESSAGE_REQUEST_TYPE_LIFEGUARD\x10\x0e\x12(\n" +
	"$CHAT_MESSAGE_REQUEST_TYPE_CHECKPOINT\x10\x0f\x12(\n" +
	"$CHAT_MESSAGE_REQUEST_TYPE_AI_GATEWAY\x10\x10\"\x04\b\b\x10\b**CHAT_MESSAGE_REQUEST_TYPE_VIBE_AND_REPLACE2}\n" +
	"\x10ApiServerService\x12i\n" +
	"\x0eGetChatMessage\x12(.exa.api_server_pb.GetChatMessageRequest\x1a).exa.api_server_pb.GetChatMessageResponse\"\x000\x01B6Z4github.com/Exafunction/Exafunction/exa/api_server_pbb\x06proto3"

var (
	file_exa_api_server_pb_api_server_proto_rawDescOnce sync.Once
	file_exa_api_server_pb_api_server_proto_rawDescData []byte
)

func file_exa_api_server_pb_api_server_proto_rawDescGZIP() []byte {
	file_exa_api_server_pb_api_server_proto_rawDescOnce.Do(func() {
		file_exa_api_server_pb_api_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exa_api_server_pb_api_server_proto_rawDesc), len(file_exa_api_server_pb_api_server_proto_rawDesc)))
	})
	return file_exa_api_server_pb_api_server_proto_rawDescData
}

var file_exa_api_server_pb_api_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_exa_api_server_pb_api_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_exa_api_server_pb_api_server_proto_goTypes = []any{
	(ChatMessageRequestType)(0),                       // 0: exa.api_server_pb.ChatMessageRequestType
	(*GetChatMessageRequest)(nil),                     // 1: exa.api_server_pb.GetChatMessageRequest
	(*GetChatMessageResponse)(nil),                    // 2: exa.api_server_pb.GetChatMessageResponse
	(*codeium_common_pb.Metadata)(nil),                // 3: exa.codeium_common_pb.Metadata
	(*chat_pb.ChatMessagePrompt)(nil),                 // 4: exa.chat_pb.ChatMessagePrompt
	(codeium_common_pb.Model)(0),                      // 5: exa.codeium_common_pb.Model
	(*codeium_common_pb.CompletionConfiguration)(nil), // 6: exa.codeium_common_pb.CompletionConfiguration
	(*codeium_common_pb.ExperimentConfig)(nil),        // 7: exa.codeium_common_pb.ExperimentConfig
	(*chat_pb.ChatToolDefinition)(nil),                // 8: exa.chat_pb.ChatToolDefinition
	(*chat_pb.ChatToolChoice)(nil),                    // 9: exa.chat_pb.ChatToolChoice
	(*chat_pb.PromptCacheOptions)(nil),                // 10: exa.chat_pb.PromptCacheOptions
	(*cortex_pb.CortexTrajectoryReference)(nil),       // 11: exa.cortex_pb.CortexTrajectoryReference
	(codeium_common_pb.ProviderSource)(0),             // 12: exa.codeium_common_pb.ProviderSource
	(codeium_common_pb.Language)(0),                   // 13: exa.codeium_common_pb.Language
	(codeium_common_pb.ConversationalPlannerMode)(0),  // 14: exa.codeium_common_pb.ConversationalPlannerMode
	(*timestamppb.Timestamp)(nil),                     // 15: google.protobuf.Timestamp
	(codeium_common_pb.StopReason)(0),                 // 16: exa.codeium_common_pb.StopReason
	(*codeium_common_pb.ChatToolCall)(nil),            // 17: exa.codeium_common_pb.ChatToolCall
	(*codeium_common_pb.ModelUsageStats)(nil),         // 18: exa.codeium_common_pb.ModelUsageStats
	(*codeium_common_pb.CompletionProfile)(nil),       // 19: exa.codeium_common_pb.CompletionProfile
	(*codeium_common_pb.ResponseDimensionGroup)(nil),  // 20: exa.codeium_common_pb.ResponseDimensionGroup
}
var file_exa_api_server_pb_api_server_proto_depIdxs = []int32{
	3,  // 0: exa.api_server_pb.GetChatMessageRequest.metadata:type_name -> exa.codeium_common_pb.Metadata
	4,  // 1: exa.api_server_pb.GetChatMessageRequest.chat_message_prompts:type_name -> exa.chat_pb.ChatMessagePrompt
	5,  // 2: exa.api_server_pb.GetChatMessageRequest.internal_chat_model:type_name -> exa.codeium_common_pb.Model
	0,  // 3: exa.api_server_pb.GetChatMessageRequest.request_type:type_name -> exa.api_server_pb.ChatMessageRequestType
	6,  // 4: exa.api_server_pb.GetChatMessageRequest.configuration:type_name -> exa.codeium_common_pb.CompletionConfiguration
	7,  // 5: exa.api_server_pb.GetChatMessageRequest.experiment_config:type_name -> exa.codeium_common_pb.ExperimentConfig
	8,  // 6: exa.api_server_pb.GetChatMessageRequest.tools:type_name -> exa.chat_pb.ChatToolDefinition
	9,  // 7: exa.api_server_pb.GetChatMessageRequest.tool_choice:type_name -> exa.chat_pb.ChatToolChoice
	10, // 8: exa.api_server_pb.GetChatMessageRequest.system_prompt_cache_options:type_name -> exa.chat_pb.PromptCacheOptions
	11, // 9: exa.api_server_pb.GetChatMessageRequest.trajectory_reference:type_name -> exa.cortex_pb.CortexTrajectoryReference
	12, // 10: exa.api_server_pb.GetChatMessageRequest.provider_source:type_name -> exa.codeium_common_pb.ProviderSource
	13, // 11: exa.api_server_pb.GetChatMessageRequest.language:type_name -> exa.codeium_common_pb.Language
	14, // 12: exa.api_server_pb.GetChatMessageRequest.planner_mode:type_name -> exa.codeium_common_pb.ConversationalPlannerMode
	15, // 13: exa.api_server_pb.GetChatMessageResponse.timestamp:type_name -> google.protobuf.Timestamp
	16, // 14: exa.api_server_pb.GetChatMessageResponse.stop_reason:type_name -> exa.codeium_common_pb.StopReason
	17, // 15: exa.api_server_pb.GetChatMessageResponse.delta_tool_calls:type_name -> exa.codeium_common_pb.ChatToolCall
	18, // 16: exa.api_server_pb.GetChatMessageResponse.usage:type_name -> exa.codeium_common_pb.ModelUsageStats
	19, // 17: exa.api_server_pb.GetChatMessageResponse.completion_profile:type_name -> exa.codeium_common_pb.CompletionProfile
	20, // 18: exa.api_server_pb.GetChatMessageResponse.response_dimension_groups:type_name -> exa.codeium_common_pb.ResponseDimensionGroup
	1,  // 19: exa.api_server_pb.ApiServerService.GetChatMessage:input_type -> exa.api_server_pb.GetChatMessageRequest
	2,  // 20: exa.api_server_pb.ApiServerService.GetChatMessage:output_type -> exa.api_server_pb.GetChatMessageResponse
	20, // [20:21] is the sub-list for method output_type
	19, // [19:20] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_exa_api_server_pb_api_server_proto_init() }
func file_exa_api_server_pb_api_server_proto_init() {
	if File_exa_api_server_pb_api_server_proto != nil {
		return
	}
	file_exa_api_server_pb_api_server_proto_msgTypes[0].OneofWrappers = []any{}
	file_exa_api_server_pb_api_server_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exa_api_server_pb_api_server_proto_rawDesc), len(file_exa_api_server_pb_api_server_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exa_api_server_pb_api_server_proto_goTypes,
		DependencyIndexes: file_exa_api_server_pb_api_server_proto_depIdxs,
		EnumInfos:         file_exa_api_server_pb_api_server_proto_enumTypes,
		MessageInfos:      file_exa_api_server_pb_api_server_proto_msgTypes,
	}.Build()
	File_exa_api_server_pb_api_server_proto = out.File
	file_exa_api_server_pb_api_server_proto_goTypes = nil
	file_exa_api_server_pb_api_server_proto_depIdxs = nil
}
