// Devin Desktop 3.10.31, linux-x64: https://windsurf-stable.codeiumdata.com/linux-x64/stable/b98cc43128712ba73c60cca73876f58a710aaa27/Devin-linux-x64-3.10.31.tar.gz
// Archive SHA256 (locally calculated): b3ddf1098c11255354d60a0778d7033989eaed85a37bbd55df90167f42eb5346
// Language server SHA256: aced58234bf6fac9cf5b65d9286e971d697b0a60baaee0a812ff0312dffb88de
// Extracted descriptor set SHA256: 9877811de3bc8055852f94aabd7c7affb3964c30f66c43b0cbcd49753abe211d
// Regenerate: bash scripts/update-devin-proto.sh --version 3.10.31
// Recovered from Desktop, not an official proto source release or a CLI compatibility guarantee.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: exa/chat_pb/chat.proto

package chat_pb

import (
	codeium_common_pb "github.com/caigee-cmd/cli2api/internal/providers/devin/devinpb/codeium_common_pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheControlType int32

const (
	CacheControlType_CACHE_CONTROL_TYPE_UNSPECIFIED CacheControlType = 0
	CacheControlType_CACHE_CONTROL_TYPE_EPHEMERAL   CacheControlType = 1
)

// Enum value maps for CacheControlType.
var (
	CacheControlType_name = map[int32]string{
		0: "CACHE_CONTROL_TYPE_UNSPECIFIED",
		1: "CACHE_CONTROL_TYPE_EPHEMERAL",
	}
	CacheControlType_value = map[string]int32{
		"CACHE_CONTROL_TYPE_UNSPECIFIED": 0,
		"CACHE_CONTROL_TYPE_EPHEMERAL":   1,
	}
)

func (x CacheControlType) Enum() *CacheControlType {
	p := new(CacheControlType)
	*p = x
	return p
}

func (x CacheControlType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CacheControlType) Descriptor() protoreflect.EnumDescriptor {
	return file_exa_chat_pb_chat_proto_enumTypes[0].Descriptor()
}

func (CacheControlType) Type() protoreflect.EnumType {
	return &file_exa_chat_pb_chat_proto_enumTypes[0]
}

func (x CacheControlType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CacheControlType.Descriptor instead.
func (CacheControlType) EnumDescriptor() ([]byte, []int) {
	return file_exa_chat_pb_chat_proto_rawDescGZIP(), []int{0}
}

type ChatMessagePrompt struct {
	state                  protoimpl.MessageState                     `protogen:"open.v1"`
	MessageId              string                                     `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Source                 codeium_common_pb.ChatMessageSource        `protobuf:"varint,2,opt,name=source,proto3,enum=exa.codeium_common_pb.ChatMessageSource" json:"source,omitempty"`
	Prompt                 string                                     `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	NumTokens              uint32                                     `protobuf:"varint,4,opt,name=num_tokens,json=numTokens,proto3" json:"num_tokens,omitempty"`
	SafeForCodeTelemetry   bool                                       `protobuf:"varint,5,opt,name=safe_for_code_telemetry,json=safeForCodeTelemetry,proto3" json:"safe_for_code_telemetry,omitempty"`
	ToolCalls              []*codeium_common_pb.ChatToolCall          `protobuf:"bytes,6,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	ToolCallId             string                                     `protobuf:"bytes,7,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	PromptCacheOptions     *PromptCacheOptions                        `protobuf:"bytes,8,opt,name=prompt_cache_options,json=promptCacheOptions,proto3" json:"prompt_cache_options,omitempty"`
	ToolResultIsError      bool                                       `protobuf:"varint,9,opt,name=tool_result_is_error,json=toolResultIsError,proto3" json:"tool_result_is_error,omitempty"`
	Images                 []*codeium_common_pb.ImageData             `protobuf:"bytes,10,rep,name=images,proto3" json:"images,omitempty"`
	Thinking               string                                     `protobuf:"bytes,11,opt,name=thinking,proto3" json:"thinking,omitempty"`
	Signature              string                                     `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"`
	ThinkingRedacted       bool                                       `protobuf:"varint,13,opt,name=thinking_redacted,json=thinkingRedacted,proto3" json:"thinking_redacted,omitempty"`
	PromptAnnotationRanges []*codeium_common_pb.PromptAnnotationRange `protobuf:"bytes,14,rep,name=prompt_annotation_ranges,json=promptAnnotationRanges,proto3" json:"prompt_annotation_ranges,omitempty"`
	OutputId               string                                     `protobuf:"bytes,15,opt,name=output_id,json=outputId,proto3" json:"output_id,omitempty"`
	// Deprecated: Marked as deprecated in exa/chat_pb/chat.proto.
	ThinkingId string `protobuf:"bytes,16,opt,name=thinking_id,json=thinkingId,proto3" json:"thinking_id,omitempty"`
	// Deprecated: Marked as deprecated in exa/chat_pb/chat.proto.
	GeminiThoughtSignature []byte                            `protobuf:"bytes,17,opt,name=gemini_thought_signature,json=geminiThoughtSignature,proto3" json:"gemini_thought_signature,omitempty"`
	SignatureType          string                            `protobuf:"bytes,18,opt,name=signature_type,json=signatureType,proto3" json:"signature_type,omitempty"`
	Phase                  string                            `protobuf:"bytes,19,opt,name=phase,proto3" json:"phase,omitempty"`
	Videos                 []*codeium_common_pb.VideoData    `protobuf:"bytes,20,rep,name=videos,proto3" json:"videos,omitempty"`
	Documents              []*codeium_common_pb.DocumentData `protobuf:"bytes,21,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ChatMessagePrompt) Reset() {
	*x = ChatMessagePrompt{}
	mi := &file_exa_chat_pb_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessagePrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessagePrompt) ProtoMessage() {}

func (x *ChatMessagePrompt) ProtoReflect() protoreflect.Message {
	mi := &file_exa_chat_pb_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessagePrompt.ProtoReflect.Descriptor instead.
func (*ChatMessagePrompt) Descriptor() ([]byte, []int) {
	return file_exa_chat_pb_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessagePrompt) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessagePrompt) GetSource() codeium_common_pb.ChatMessageSource {
	if x != nil {
		return x.Source
	}
	return codeium_common_pb.ChatMessageSource(0)
}

func (x *ChatMessagePrompt) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ChatMessagePrompt) GetNumTokens() uint32 {
	if x != nil {
		return x.NumTokens
	}
	return 0
}

func (x *ChatMessagePrompt) GetSafeForCodeTelemetry() bool {
	if x != nil {
		return x.SafeForCodeTelemetry
	}
	return false
}

func (x *ChatMessagePrompt) GetToolCalls() []*codeium_common_pb.ChatToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *ChatMessagePrompt) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ChatMessagePrompt) GetPromptCacheOptions() *PromptCacheOptions {
	if x != nil {
		return x.PromptCacheOptions
	}
	return nil
}

func (x *ChatMessagePrompt) GetToolResultIsError() bool {
	if x != nil {
		return x.ToolResultIsError
	}
	return false
}

func (x *ChatMessagePrompt) GetImages() []*codeium_common_pb.ImageData {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ChatMessagePrompt) GetThinking() string {
	if x != nil {
		return x.Thinking
	}
	return ""
}

func (x *ChatMessagePrompt) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ChatMessagePrompt) GetThinkingRedacted() bool {
	if x != nil {
		return x.ThinkingRedacted
	}
	return false
}

func (x *ChatMessagePrompt) GetPromptAnnotationRanges() []*codeium_common_pb.PromptAnnotationRange {
	if x != nil {
		return x.PromptAnnotationRanges
	}
	return nil
}

func (x *ChatMessagePrompt) GetOutputId() string {
	if x != nil {
		return x.OutputId
	}
	return ""
}

// Deprecated: Marked as deprecated in exa/chat_pb/chat.proto.
func (x *ChatMessagePrompt) GetThinkingId() string {
	if x != nil {
		return x.ThinkingId
	}
	return ""
}

// Deprecated: Marked as deprecated in exa/chat_pb/chat.proto.
func (x *ChatMessagePrompt) GetGeminiThoughtSignature() []byte {
	if x != nil {
		return x.GeminiThoughtSignature
	}
	return nil
}

func (x *ChatMessagePrompt) GetSignatureType() string {
	if x != nil {
		return x.SignatureType
	}
	return ""
}

func (x *ChatMessagePrompt) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ChatMessagePrompt) GetVideos() []*codeium_common_pb.VideoData {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *ChatMessagePrompt) GetDocuments() []*codeium_common_pb.DocumentData {
	if x != nil {
		return x.Documents
	}
	return nil
}

type PromptCacheOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CacheControlType       `protobuf:"varint,1,opt,name=type,proto3,enum=exa.chat_pb.CacheControlType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptCacheOptions) Reset() {
	*x = PromptCacheOptions{}
	mi := &file_exa_chat_pb_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptCacheOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptCacheOptions) ProtoMessage() {}

func (x *PromptCacheOptions) ProtoReflect() protoreflect.Message {
	mi := &file_exa_chat_pb_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptCacheOptions.ProtoReflect.Descriptor instead.
func (*PromptCacheOptions) Descriptor() ([]byte, []int) {
	return file_exa_chat_pb_chat_proto_rawDescGZIP(), []int{1}
}

func (x *PromptCacheOptions) GetType() CacheControlType {
	if x != nil {
		return x.Type
	}
	return CacheControlType_CACHE_CONTROL_TYPE_UNSPECIFIED
}

type ChatToolDefinition struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Name                    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description             string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	JsonSchemaString        string                 `protobuf:"bytes,3,opt,name=json_schema_string,json=jsonSchemaString,proto3" json:"json_schema_string,omitempty"`
	AttributionFieldNames   []string               `protobuf:"bytes,5,rep,name=attribution_field_names,json=attributionFieldNames,proto3" json:"attribution_field_names,omitempty"`
	ServerName              string                 `protobuf:"bytes,6,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ReadOnlyHint            *bool                  `protobuf:"varint,7,opt,name=read_only_hint,json=readOnlyHint,proto3,oneof" json:"read_only_hint,omitempty"`
	ComputerUseConfig       *ComputerUseToolConfig `protobuf:"bytes,8,opt,name=computer_use_config,json=computerUseConfig,proto3,oneof" json:"computer_use_config,omitempty"`
	IsCustomTool            *bool                  `protobuf:"varint,9,opt,name=is_custom_tool,json=isCustomTool,proto3,oneof" json:"is_custom_tool,omitempty"`
	CustomToolGrammar       *string                `protobuf:"bytes,10,opt,name=custom_tool_grammar,json=customToolGrammar,proto3,oneof" json:"custom_tool_grammar,omitempty"`
	CustomToolGrammarSyntax *string                `protobuf:"bytes,11,opt,name=custom_tool_grammar_syntax,json=customToolGrammarSyntax,proto3,oneof" json:"custom_tool_grammar_syntax,omitempty"`
	Strict                  bool                   `protobuf:"varint,12,opt,name=strict,proto3" json:"strict,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ChatToolDefinition) Reset() {
	*x = ChatToolDefinition{}
	mi := &file_exa_chat_pb_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatToolDefinition) ProtoMessage() {}

func (x *ChatToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_exa_chat_pb_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatToolDefinition.ProtoReflect.Descriptor instead.
func (*ChatToolDefinition) Descriptor() ([]byte, []int) {
	return file_exa_chat_pb_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ChatToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChatToolDefinition) GetJsonSchemaString() string {
	if x != nil {
		return x.JsonSchemaString
	}
	return ""
}

func (x *ChatToolDefinition) GetAttributionFieldNames() []string {
	if x != nil {
		return x.AttributionFieldNames
	}
	return nil
}

func (x *ChatToolDefinition) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ChatToolDefinition) GetReadOnlyHint() bool {
	if x != nil && x.ReadOnlyHint != nil {
		return *x.ReadOnlyHint
	}
	return false
}

func (x *ChatToolDefinition) GetComputerUseConfig() *ComputerUseToolConfig {
	if x != nil {
		return x.ComputerUseConfig
	}
	return nil
}

func (x *ChatToolDefinition) GetIsCustomTool() bool {
	if x != nil && x.IsCustomTool != nil {
		return *x.IsCustomTool
	}
	return false
}

func (x *ChatToolDefinition) GetCustomToolGrammar() string {
	if x != nil && x.CustomToolGrammar != nil {
		return *x.CustomToolGrammar
	}
	return ""
}

func (x *ChatToolDefinition) GetCustomToolGrammarSyntax() string {
	if x != nil && x.CustomToolGrammarSyntax != nil {
		return *x.CustomToolGrammarSyntax
	}
	return ""
}

func (x *ChatToolDefinition) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

type ComputerUseToolConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DisplayWidthPx  int32                  `protobuf:"varint,1,opt,name=display_width_px,json=displayWidthPx,proto3" json:"display_width_px,omitempty"`
	DisplayHeightPx int32                  `protobuf:"varint,2,opt,name=display_height_px,json=displayHeightPx,proto3" json:"display_height_px,omitempty"`
	DisplayNumber   int32                  `protobuf:"varint,3,opt,name=display_number,json=displayNumber,proto3" json:"display_number,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ComputerUseToolConfig) Reset() {
	*x = ComputerUseToolConfig{}
	mi := &file_exa_chat_pb_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputerUseToolConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputerUseToolConfig) ProtoMessage() {}

func (x *ComputerUseToolConfig) ProtoReflect() protoreflect.Message {
	mi := &file_exa_chat_pb_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputerUseToolConfig.ProtoReflect.Descriptor instead.
func (*ComputerUseToolConfig) Descriptor() ([]byte, []int) {
	return file_exa_chat_pb_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ComputerUseToolConfig) GetDisplayWidthPx() int32 {
	if x != nil {
		return x.DisplayWidthPx
	}
	return 0
}

func (x *ComputerUseToolConfig) GetDisplayHeightPx() int32 {
	if x != nil {
		return x.DisplayHeightPx
	}
	return 0
}

func (x *ComputerUseToolConfig) GetDisplayNumber() int32 {
	if x != nil {
		return x.DisplayNumber
	}
	return 0
}

type ChatToolChoice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Choice:
	//
	//	*ChatToolChoice_OptionName
	//	*ChatToolChoice_ToolName
	Choice        isChatToolChoice_Choice `protobuf_oneof:"choice"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatToolChoice) Reset() {
	*x = ChatToolChoice{}
	mi := &file_exa_chat_pb_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatToolChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatToolChoice) ProtoMessage() {}

func (x *ChatToolChoice) ProtoReflect() protoreflect.Message {
	mi := &file_exa_chat_pb_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatToolChoice.ProtoReflect.Descriptor instead.
func (*ChatToolChoice) Descriptor() ([]byte, []int) {
	return file_exa_chat_pb_chat_proto_rawDescGZIP(), []int{4}
}

func (x *ChatToolChoice) GetChoice() isChatToolChoice_Choice {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *ChatToolChoice) GetOptionName() string {
	if x != nil {
		if x, ok := x.Choice.(*ChatToolChoice_OptionName); ok {
			return x.OptionName
		}
	}
	return ""
}

func (x *ChatToolChoice) GetToolName() string {
	if x != nil {
		if x, ok := x.Choice.(*ChatToolChoice_ToolName); ok {
			return x.ToolName
		}
	}
	return ""
}

type isChatToolChoice_Choice interface {
	isChatToolChoice_Choice()
}

type ChatToolChoice_OptionName struct {
	OptionName string `protobuf:"bytes,1,opt,name=option_name,json=optionName,proto3,oneof"`
}

type ChatToolChoice_ToolName struct {
	ToolName string `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3,oneof"`
}

func (*ChatToolChoice_OptionName) isChatToolChoice_Choice() {}

func (*ChatToolChoice_ToolName) isChatToolChoice_Choice() {}

var File_exa_chat_pb_chat_proto protoreflect.FileDescriptor

const file_exa_chat_pb_chat_proto_rawDesc = "" +
	"\n" +
	"\x16exa/chat_pb/chat.proto\x12\vexa.chat_pb\x1a*exa/codeium_common_pb/codeium_common.proto\"\x8f\b\n" +
	"\x11ChatMessagePrompt\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12@\n" +
	"\x06source\x18\x02 \x01(\x0e2(.exa.codeium_common_pb.ChatMessageSourceR\x06source\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"num_tokens\x18\x04 \x01(\rR\tnumTokens\x125\n" +
	"\x17safe_for_code_telemetry\x18\x05 \x01(\bR\x14safeForCodeTelemetry\x12B\n" +
	"\n" +
	"tool_calls\x18\x06 \x03(\v2#.exa.codeium_common_pb.ChatToolCallR\ttoolCalls\x12 \n" +
	"\ftool_call_id\x18\a \x01(\tR\n" +
	"toolCallId\x12Q\n" +
	"\x14prompt_cache_options\x18\b \x01(\v2\x1f.exa.chat_pb.PromptCacheOptionsR\x12promptCacheOptions\x12/\n" +
	"\x14tool_result_is_error\x18\t \x01(\bR\x11toolResultIsError\x128\n" +
	"\x06images\x18\n" +
	" \x03(\v2 .exa.codeium_common_pb.ImageDataR\x06images\x12\x1a\n" +
	"\bthinking\x18\v \x01(\tR\bthinking\x12\x1c\n" +
	"\tsignature\x18\f \x01(\tR\tsignature\x12+\n" +
	"\x11thinking_redacted\x18\r \x01(\bR\x10thinkingRedacted\x12f\n" +
	"\x18prompt_annotation_ranges\x18\x0e \x03(\v2,.exa.codeium_common_pb.PromptAnnotationRangeR\x16promptAnnotationRanges\x12\x1b\n" +
	"\toutput_id\x18\x0f \x01(\tR\boutputId\x12#\n" +
	"\vthinking_id\x18\x10 \x01(\tB\x02\x18\x01R\n" +
	"thinkingId\x12<\n" +
	"\x18gemini_thought_signature\x18\x11 \x01(\fB\x02\x18\x01R\x16geminiThoughtSignature\x12%\n" +
	"\x0esignature_type\x18\x12 \x01(\tR\rsignatureType\x12\x14\n" +
	"\x05phase\x18\x13 \x01(\tR\x05phase\x128\n" +
	"\x06videos\x18\x14 \x03(\v2 .exa.codeium_common_pb.VideoDataR\x06videos\x12A\n" +
	"\tdocuments\x18\x15 \x03(\v2#.exa.codeium_common_pb.DocumentDataR\tdocuments\"G\n" +
	"\x12PromptCacheOptions\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.exa.chat_pb.CacheControlTypeR\x04type\"\xa3\x05\n" +
	"\x12ChatToolDefinition\x12+\n" +
	"\x04name\x18\x01 \x01(\tB\x17\xbaH\x14r\x122\x10^[a-zA-Z0-9_-]+$R\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12,\n" +
	"\x12json_schema_string\x18\x03 \x01(\tR\x10jsonSchemaString\x126\n" +
	"\x17attribution_field_names\x18\x05 \x03(\tR\x15attributionFieldNames\x12\x1f\n" +
	"\vserver_name\x18\x06 \x01(\tR\n" +
	"serverName\x12)\n" +
	"\x0eread_only_hint\x18\a \x01(\bH\x00R\freadOnlyHint\x88\x01\x01\x12W\n" +
	"\x13computer_use_config\x18\b \x01(\v2\".exa.chat_pb.ComputerUseToolConfigH\x01R\x11computerUseConfig\x88\x01\x01\x12)\n" +
	"\x0eis_custom_tool\x18\t \x01(\bH\x02R\fisCustomTool\x88\x01\x01\x123\n" +
	"\x13custom_tool_grammar\x18\n" +
	" \x01(\tH\x03R\x11customToolGrammar\x88\x01\x01\x12@\n" +
	"\x1acustom_tool_grammar_syntax\x18\v \x01(\tH\x04R\x17customToolGrammarSyntax\x88\x01\x01\x12\x16\n" +
	"\x06strict\x18\f \x01(\bR\x06strictB\x11\n" +
	"\x0f_read_only_hintB\x16\n" +
	"\x14_computer_use_configB\x11\n" +
	"\x0f_is_custom_toolB\x16\n" +
	"\x14_custom_tool_grammarB\x1d\n" +
	"\x1b_custom_tool_grammar_syntaxJ\x04\b\x04\x10\x05\"\x94\x01\n" +
	"\x15ComputerUseToolConfig\x12(\n" +
	"\x10display_width_px\x18\x01 \x01(\x05R\x0edisplayWidthPx\x12*\n" +
	"\x11display_height_px\x18\x02 \x01(\x05R\x0fdisplayHeightPx\x12%\n" +
	"\x0edisplay_number\x18\x03 \x01(\x05R\rdisplayNumber\"\\\n" +
	"\x0eChatToolChoice\x12!\n" +
	"\voption_name\x18\x01 \x01(\tH\x00R\n" +
	"optionName\x12\x1d\n" +
	"\ttool_name\x18\x02 \x01(\tH\x00R\btoolNameB\b\n" +
	"\x06choice*X\n" +
	"\x10CacheControlType\x12\"\n" +
	"\x1eCACHE_CONTROL_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCACHE_CONTROL_TYPE_EPHEMERAL\x10\x01B0Z.github.com/Exafunction/Exafunction/exa/chat_pbb\x06proto3"

var (
	file_exa_chat_pb_chat_proto_rawDescOnce sync.Once
	file_exa_chat_pb_chat_proto_rawDescData []byte
)

func file_exa_chat_pb_chat_proto_rawDescGZIP() []byte {
	file_exa_chat_pb_chat_proto_rawDescOnce.Do(func() {
		file_exa_chat_pb_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exa_chat_pb_chat_proto_rawDesc), len(file_exa_chat_pb_chat_proto_rawDesc)))
	})
	return file_exa_chat_pb_chat_proto_rawDescData
}

var file_exa_chat_pb_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_exa_chat_pb_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_exa_chat_pb_chat_proto_goTypes = []any{
	(CacheControlType)(0),                           // 0: exa.chat_pb.CacheControlType
	(*ChatMessagePrompt)(nil),                       // 1: exa.chat_pb.ChatMessagePrompt
	(*PromptCacheOptions)(nil),                      // 2: exa.chat_pb.PromptCacheOptions
	(*ChatToolDefinition)(nil),                      // 3: exa.chat_pb.ChatToolDefinition
	(*ComputerUseToolConfig)(nil),                   // 4: exa.chat_pb.ComputerUseToolConfig
	(*ChatToolChoice)(nil),                          // 5: exa.chat_pb.ChatToolChoice
	(codeium_common_pb.ChatMessageSource)(0),        // 6: exa.codeium_common_pb.ChatMessageSource
	(*codeium_common_pb.ChatToolCall)(nil),          // 7: exa.codeium_common_pb.ChatToolCall
	(*codeium_common_pb.ImageData)(nil),             // 8: exa.codeium_common_pb.ImageData
	(*codeium_common_pb.PromptAnnotationRange)(nil), // 9: exa.codeium_common_pb.PromptAnnotationRange
	(*codeium_common_pb.VideoData)(nil),             // 10: exa.codeium_common_pb.VideoData
	(*codeium_common_pb.DocumentData)(nil),          // 11: exa.codeium_common_pb.DocumentData
}
var file_exa_chat_pb_chat_proto_depIdxs = []int32{
	6,  // 0: exa.chat_pb.ChatMessagePrompt.source:type_name -> exa.codeium_common_pb.ChatMessageSource
	7,  // 1: exa.chat_pb.ChatMessagePrompt.tool_calls:type_name -> exa.codeium_common_pb.ChatToolCall
	2,  // 2: exa.chat_pb.ChatMessagePrompt.prompt_cache_options:type_name -> exa.chat_pb.PromptCacheOptions
	8,  // 3: exa.chat_pb.ChatMessagePrompt.images:type_name -> exa.codeium_common_pb.ImageData
	9,  // 4: exa.chat_pb.ChatMessagePrompt.prompt_annotation_ranges:type_name -> exa.codeium_common_pb.PromptAnnotationRange
	10, // 5: exa.chat_pb.ChatMessagePrompt.videos:type_name -> exa.codeium_common_pb.VideoData
	11, // 6: exa.chat_pb.ChatMessagePrompt.documents:type_name -> exa.codeium_common_pb.DocumentData
	0,  // 7: exa.chat_pb.PromptCacheOptions.type:type_name -> exa.chat_pb.CacheControlType
	4,  // 8: exa.chat_pb.ChatToolDefinition.computer_use_config:type_name -> exa.chat_pb.ComputerUseToolConfig
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_exa_chat_pb_chat_proto_init() }
func file_exa_chat_pb_chat_proto_init() {
	if File_exa_chat_pb_chat_proto != nil {
		return
	}
	file_exa_chat_pb_chat_proto_msgTypes[2].OneofWrappers = []any{}
	file_exa_chat_pb_chat_proto_msgTypes[4].OneofWrappers = []any{
		(*ChatToolChoice_OptionName)(nil),
		(*ChatToolChoice_ToolName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exa_chat_pb_chat_proto_rawDesc), len(file_exa_chat_pb_chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exa_chat_pb_chat_proto_goTypes,
		DependencyIndexes: file_exa_chat_pb_chat_proto_depIdxs,
		EnumInfos:         file_exa_chat_pb_chat_proto_enumTypes,
		MessageInfos:      file_exa_chat_pb_chat_proto_msgTypes,
	}.Build()
	File_exa_chat_pb_chat_proto = out.File
	file_exa_chat_pb_chat_proto_goTypes = nil
	file_exa_chat_pb_chat_proto_depIdxs = nil
}
