// Devin Desktop 3.10.31, linux-x64: https://windsurf-stable.codeiumdata.com/linux-x64/stable/b98cc43128712ba73c60cca73876f58a710aaa27/Devin-linux-x64-3.10.31.tar.gz
// Archive SHA256 (locally calculated): b3ddf1098c11255354d60a0778d7033989eaed85a37bbd55df90167f42eb5346
// Language server SHA256: aced58234bf6fac9cf5b65d9286e971d697b0a60baaee0a812ff0312dffb88de
// Extracted descriptor set SHA256: 9877811de3bc8055852f94aabd7c7affb3964c30f66c43b0cbcd49753abe211d
// Regenerate: bash scripts/update-devin-proto.sh --version 3.10.31
// Recovered from Desktop, not an official proto source release or a CLI compatibility guarantee.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: exa/seat_management_pb/seat_management.proto

package seat_management_pb

import (
	codeium_common_pb "github.com/caigee-cmd/cli2api/internal/providers/devin/devinpb/codeium_common_pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserStatusRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Metadata      *codeium_common_pb.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatusRequest) Reset() {
	*x = GetUserStatusRequest{}
	mi := &file_exa_seat_management_pb_seat_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatusRequest) ProtoMessage() {}

func (x *GetUserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exa_seat_management_pb_seat_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatusRequest.ProtoReflect.Descriptor instead.
func (*GetUserStatusRequest) Descriptor() ([]byte, []int) {
	return file_exa_seat_management_pb_seat_management_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserStatusRequest) GetMetadata() *codeium_common_pb.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetUserStatusResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	UserStatus    *codeium_common_pb.UserStatus `protobuf:"bytes,1,opt,name=user_status,json=userStatus,proto3" json:"user_status,omitempty"`
	PlanInfo      *codeium_common_pb.PlanInfo   `protobuf:"bytes,2,opt,name=plan_info,json=planInfo,proto3" json:"plan_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatusResponse) Reset() {
	*x = GetUserStatusResponse{}
	mi := &file_exa_seat_management_pb_seat_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatusResponse) ProtoMessage() {}

func (x *GetUserStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exa_seat_management_pb_seat_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatusResponse.ProtoReflect.Descriptor instead.
func (*GetUserStatusResponse) Descriptor() ([]byte, []int) {
	return file_exa_seat_management_pb_seat_management_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserStatusResponse) GetUserStatus() *codeium_common_pb.UserStatus {
	if x != nil {
		return x.UserStatus
	}
	return nil
}

func (x *GetUserStatusResponse) GetPlanInfo() *codeium_common_pb.PlanInfo {
	if x != nil {
		return x.PlanInfo
	}
	return nil
}

var File_exa_seat_management_pb_seat_management_proto protoreflect.FileDescriptor

const file_exa_seat_management_pb_seat_management_proto_rawDesc = "" +
	"\n" +
	",exa/seat_management_pb/seat_management.proto\x12\x16exa.seat_management_pb\x1a*exa/codeium_common_pb/codeium_common.proto\"[\n" +
	"\x14GetUserStatusRequest\x12C\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.exa.codeium_common_pb.MetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\"\x99\x01\n" +
	"\x15GetUserStatusResponse\x12B\n" +
	"\vuser_status\x18\x01 \x01(\v2!.exa.codeium_common_pb.UserStatusR\n" +
	"userStatus\x12<\n" +
	"\tplan_info\x18\x02 \x01(\v2\x1f.exa.codeium_common_pb.PlanInfoR\bplanInfo2\x87\x01\n" +
	"\x15SeatManagementService\x12n\n" +
	"\rGetUserStatus\x12,.exa.seat_management_pb.GetUserStatusRequest\x1a-.exa.seat_management_pb.GetUserStatusResponse\"\x00B;Z9github.com/Exafunction/Exafunction/exa/seat_management_pbb\x06proto3"

var (
	file_exa_seat_management_pb_seat_management_proto_rawDescOnce sync.Once
	file_exa_seat_management_pb_seat_management_proto_rawDescData []byte
)

func file_exa_seat_management_pb_seat_management_proto_rawDescGZIP() []byte {
	file_exa_seat_management_pb_seat_management_proto_rawDescOnce.Do(func() {
		file_exa_seat_management_pb_seat_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exa_seat_management_pb_seat_management_proto_rawDesc), len(file_exa_seat_management_pb_seat_management_proto_rawDesc)))
	})
	return file_exa_seat_management_pb_seat_management_proto_rawDescData
}

var file_exa_seat_management_pb_seat_management_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_exa_seat_management_pb_seat_management_proto_goTypes = []any{
	(*GetUserStatusRequest)(nil),         // 0: exa.seat_management_pb.GetUserStatusRequest
	(*GetUserStatusResponse)(nil),        // 1: exa.seat_management_pb.GetUserStatusResponse
	(*codeium_common_pb.Metadata)(nil),   // 2: exa.codeium_common_pb.Metadata
	(*codeium_common_pb.UserStatus)(nil), // 3: exa.codeium_common_pb.UserStatus
	(*codeium_common_pb.PlanInfo)(nil),   // 4: exa.codeium_common_pb.PlanInfo
}
var file_exa_seat_management_pb_seat_management_proto_depIdxs = []int32{
	2, // 0: exa.seat_management_pb.GetUserStatusRequest.metadata:type_name -> exa.codeium_common_pb.Metadata
	3, // 1: exa.seat_management_pb.GetUserStatusResponse.user_status:type_name -> exa.codeium_common_pb.UserStatus
	4, // 2: exa.seat_management_pb.GetUserStatusResponse.plan_info:type_name -> exa.codeium_common_pb.PlanInfo
	0, // 3: exa.seat_management_pb.SeatManagementService.GetUserStatus:input_type -> exa.seat_management_pb.GetUserStatusRequest
	1, // 4: exa.seat_management_pb.SeatManagementService.GetUserStatus:output_type -> exa.seat_management_pb.GetUserStatusResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_exa_seat_management_pb_seat_management_proto_init() }
func file_exa_seat_management_pb_seat_management_proto_init() {
	if File_exa_seat_management_pb_seat_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exa_seat_management_pb_seat_management_proto_rawDesc), len(file_exa_seat_management_pb_seat_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exa_seat_management_pb_seat_management_proto_goTypes,
		DependencyIndexes: file_exa_seat_management_pb_seat_management_proto_depIdxs,
		MessageInfos:      file_exa_seat_management_pb_seat_management_proto_msgTypes,
	}.Build()
	File_exa_seat_management_pb_seat_management_proto = out.File
	file_exa_seat_management_pb_seat_management_proto_goTypes = nil
	file_exa_seat_management_pb_seat_management_proto_depIdxs = nil
}
