// Devin Desktop 3.10.31, linux-x64: https://windsurf-stable.codeiumdata.com/linux-x64/stable/b98cc43128712ba73c60cca73876f58a710aaa27/Devin-linux-x64-3.10.31.tar.gz
// Archive SHA256 (locally calculated): b3ddf1098c11255354d60a0778d7033989eaed85a37bbd55df90167f42eb5346
// Language server SHA256: aced58234bf6fac9cf5b65d9286e971d697b0a60baaee0a812ff0312dffb88de
// Extracted descriptor set SHA256: 9877811de3bc8055852f94aabd7c7affb3964c30f66c43b0cbcd49753abe211d
// Regenerate: bash scripts/update-devin-proto.sh --version 3.10.31
// Recovered from Desktop, not an official proto source release or a CLI compatibility guarantee.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: exa/cortex_pb/cortex.proto

package cortex_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CortexTrajectoryType int32

const (
	CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_UNSPECIFIED   CortexTrajectoryType = 0
	CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_USER_MAINLINE CortexTrajectoryType = 1
	CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_USER_GRANULAR CortexTrajectoryType = 2
	CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_SUPERCOMPLETE CortexTrajectoryType = 3
	CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_CASCADE       CortexTrajectoryType = 4
	// Deprecated: Marked as deprecated in exa/cortex_pb/cortex.proto.
	CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_BACKGROUND_RESEARCH  CortexTrajectoryType = 5
	CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_CHECKPOINT           CortexTrajectoryType = 6
	CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_RETRIEVE_MEMORY      CortexTrajectoryType = 7
	CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_CUSTOM_TOOL          CortexTrajectoryType = 8
	CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_AUTO_CASCADE         CortexTrajectoryType = 9
	CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_AUTO_CASCADE_MANAGER CortexTrajectoryType = 10
	CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_APPLIER              CortexTrajectoryType = 11
	CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_TOOL_CALL_PROPOSAL   CortexTrajectoryType = 12
	CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_TRAJECTORY_CHOICE    CortexTrajectoryType = 13
	CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_LLM_JUDGE            CortexTrajectoryType = 14
	// Deprecated: Marked as deprecated in exa/cortex_pb/cortex.proto.
	CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_ARTIFACT_SUMMARY    CortexTrajectoryType = 19
	CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_PASSIVE_CODER       CortexTrajectoryType = 15
	CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_INTERACTIVE_CASCADE CortexTrajectoryType = 17
	CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_BRAIN_UPDATE        CortexTrajectoryType = 16
	CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_AI_GATEWAY          CortexTrajectoryType = 22
)

// Enum value maps for CortexTrajectoryType.
var (
	CortexTrajectoryType_name = map[int32]string{
		0:  "CORTEX_TRAJECTORY_TYPE_UNSPECIFIED",
		1:  "CORTEX_TRAJECTORY_TYPE_USER_MAINLINE",
		2:  "CORTEX_TRAJECTORY_TYPE_USER_GRANULAR",
		3:  "CORTEX_TRAJECTORY_TYPE_SUPERCOMPLETE",
		4:  "CORTEX_TRAJECTORY_TYPE_CASCADE",
		5:  "CORTEX_TRAJECTORY_TYPE_BACKGROUND_RESEARCH",
		6:  "CORTEX_TRAJECTORY_TYPE_CHECKPOINT",
		7:  "CORTEX_TRAJECTORY_TYPE_RETRIEVE_MEMORY",
		8:  "CORTEX_TRAJECTORY_TYPE_CUSTOM_TOOL",
		9:  "CORTEX_TRAJECTORY_TYPE_AUTO_CASCADE",
		10: "CORTEX_TRAJECTORY_TYPE_AUTO_CASCADE_MANAGER",
		11: "CORTEX_TRAJECTORY_TYPE_APPLIER",
		12: "CORTEX_TRAJECTORY_TYPE_TOOL_CALL_PROPOSAL",
		13: "CORTEX_TRAJECTORY_TYPE_TRAJECTORY_CHOICE",
		14: "CORTEX_TRAJECTORY_TYPE_LLM_JUDGE",
		19: "CORTEX_TRAJECTORY_TYPE_ARTIFACT_SUMMARY",
		15: "CORTEX_TRAJECTORY_TYPE_PASSIVE_CODER",
		17: "CORTEX_TRAJECTORY_TYPE_INTERACTIVE_CASCADE",
		16: "CORTEX_TRAJECTORY_TYPE_BRAIN_UPDATE",
		22: "CORTEX_TRAJECTORY_TYPE_AI_GATEWAY",
	}
	CortexTrajectoryType_value = map[string]int32{
		"CORTEX_TRAJECTORY_TYPE_UNSPECIFIED":          0,
		"CORTEX_TRAJECTORY_TYPE_USER_MAINLINE":        1,
		"CORTEX_TRAJECTORY_TYPE_USER_GRANULAR":        2,
		"CORTEX_TRAJECTORY_TYPE_SUPERCOMPLETE":        3,
		"CORTEX_TRAJECTORY_TYPE_CASCADE":              4,
		"CORTEX_TRAJECTORY_TYPE_BACKGROUND_RESEARCH":  5,
		"CORTEX_TRAJECTORY_TYPE_CHECKPOINT":           6,
		"CORTEX_TRAJECTORY_TYPE_RETRIEVE_MEMORY":      7,
		"CORTEX_TRAJECTORY_TYPE_CUSTOM_TOOL":          8,
		"CORTEX_TRAJECTORY_TYPE_AUTO_CASCADE":         9,
		"CORTEX_TRAJECTORY_TYPE_AUTO_CASCADE_MANAGER": 10,
		"CORTEX_TRAJECTORY_TYPE_APPLIER":              11,
		"CORTEX_TRAJECTORY_TYPE_TOOL_CALL_PROPOSAL":   12,
		"CORTEX_TRAJECTORY_TYPE_TRAJECTORY_CHOICE":    13,
		"CORTEX_TRAJECTORY_TYPE_LLM_JUDGE":            14,
		"CORTEX_TRAJECTORY_TYPE_ARTIFACT_SUMMARY":     19,
		"CORTEX_TRAJECTORY_TYPE_PASSIVE_CODER":        15,
		"CORTEX_TRAJECTORY_TYPE_INTERACTIVE_CASCADE":  17,
		"CORTEX_TRAJECTORY_TYPE_BRAIN_UPDATE":         16,
		"CORTEX_TRAJECTORY_TYPE_AI_GATEWAY":           22,
	}
)

func (x CortexTrajectoryType) Enum() *CortexTrajectoryType {
	p := new(CortexTrajectoryType)
	*p = x
	return p
}

func (x CortexTrajectoryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CortexTrajectoryType) Descriptor() protoreflect.EnumDescriptor {
	return file_exa_cortex_pb_cortex_proto_enumTypes[0].Descriptor()
}

func (CortexTrajectoryType) Type() protoreflect.EnumType {
	return &file_exa_cortex_pb_cortex_proto_enumTypes[0]
}

func (x CortexTrajectoryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CortexTrajectoryType.Descriptor instead.
func (CortexTrajectoryType) EnumDescriptor() ([]byte, []int) {
	return file_exa_cortex_pb_cortex_proto_rawDescGZIP(), []int{0}
}

type CortexStepType int32

const (
	CortexStepType_CORTEX_STEP_TYPE_UNSPECIFIED    CortexStepType = 0
	CortexStepType_CORTEX_STEP_TYPE_DUMMY          CortexStepType = 1
	CortexStepType_CORTEX_STEP_TYPE_FINISH         CortexStepType = 2
	CortexStepType_CORTEX_STEP_TYPE_PLAN_INPUT     CortexStepType = 3
	CortexStepType_CORTEX_STEP_TYPE_MQUERY         CortexStepType = 4
	CortexStepType_CORTEX_STEP_TYPE_CODE_ACTION    CortexStepType = 5
	CortexStepType_CORTEX_STEP_TYPE_GIT_COMMIT     CortexStepType = 6
	CortexStepType_CORTEX_STEP_TYPE_GREP_SEARCH    CortexStepType = 7
	CortexStepType_CORTEX_STEP_TYPE_VIEW_FILE      CortexStepType = 8
	CortexStepType_CORTEX_STEP_TYPE_LIST_DIRECTORY CortexStepType = 9
	CortexStepType_CORTEX_STEP_TYPE_COMPILE        CortexStepType = 10
	CortexStepType_CORTEX_STEP_TYPE_INFORM         CortexStepType = 11
	// Deprecated: Marked as deprecated in exa/cortex_pb/cortex.proto.
	CortexStepType_CORTEX_STEP_TYPE_FILE_BREAKDOWN   CortexStepType = 12
	CortexStepType_CORTEX_STEP_TYPE_VIEW_CODE_ITEM   CortexStepType = 13
	CortexStepType_CORTEX_STEP_TYPE_USER_INPUT       CortexStepType = 14
	CortexStepType_CORTEX_STEP_TYPE_PLANNER_RESPONSE CortexStepType = 15
	// Deprecated: Marked as deprecated in exa/cortex_pb/cortex.proto.
	CortexStepType_CORTEX_STEP_TYPE_WRITE_TO_FILE   CortexStepType = 16
	CortexStepType_CORTEX_STEP_TYPE_ERROR_MESSAGE   CortexStepType = 17
	CortexStepType_CORTEX_STEP_TYPE_CLUSTER_QUERY   CortexStepType = 18
	CortexStepType_CORTEX_STEP_TYPE_LIST_CLUSTERS   CortexStepType = 19
	CortexStepType_CORTEX_STEP_TYPE_INSPECT_CLUSTER CortexStepType = 20
	CortexStepType_CORTEX_STEP_TYPE_RUN_COMMAND     CortexStepType = 21
	CortexStepType_CORTEX_STEP_TYPE_RELATED_FILES   CortexStepType = 22
	CortexStepType_CORTEX_STEP_TYPE_CHECKPOINT      CortexStepType = 23
	CortexStepType_CORTEX_STEP_TYPE_PROPOSE_CODE    CortexStepType = 24
	CortexStepType_CORTEX_STEP_TYPE_FIND            CortexStepType = 25
	// Deprecated: Marked as deprecated in exa/cortex_pb/cortex.proto.
	CortexStepType_CORTEX_STEP_TYPE_SEARCH_KNOWLEDGE_BASE CortexStepType = 26
	CortexStepType_CORTEX_STEP_TYPE_SUGGESTED_RESPONSES   CortexStepType = 27
	CortexStepType_CORTEX_STEP_TYPE_COMMAND_STATUS        CortexStepType = 28
	CortexStepType_CORTEX_STEP_TYPE_MEMORY                CortexStepType = 29
	// Deprecated: Marked as deprecated in exa/cortex_pb/cortex.proto.
	CortexStepType_CORTEX_STEP_TYPE_LOOKUP_KNOWLEDGE_BASE  CortexStepType = 30
	CortexStepType_CORTEX_STEP_TYPE_READ_URL_CONTENT       CortexStepType = 31
	CortexStepType_CORTEX_STEP_TYPE_VIEW_CONTENT_CHUNK     CortexStepType = 32
	CortexStepType_CORTEX_STEP_TYPE_SEARCH_WEB             CortexStepType = 33
	CortexStepType_CORTEX_STEP_TYPE_RETRIEVE_MEMORY        CortexStepType = 34
	CortexStepType_CORTEX_STEP_TYPE_AUTO_CASCADE_BROADCAST CortexStepType = 35
	CortexStepType_CORTEX_STEP_TYPE_CUSTOM_TOOL            CortexStepType = 36
	// Deprecated: Marked as deprecated in exa/cortex_pb/cortex.proto.
	CortexStepType_CORTEX_STEP_TYPE_CREATE_RECIPE          CortexStepType = 37
	CortexStepType_CORTEX_STEP_TYPE_MCP_TOOL               CortexStepType = 38
	CortexStepType_CORTEX_STEP_TYPE_MANAGER_FEEDBACK       CortexStepType = 39
	CortexStepType_CORTEX_STEP_TYPE_TOOL_CALL_PROPOSAL     CortexStepType = 40
	CortexStepType_CORTEX_STEP_TYPE_TOOL_CALL_CHOICE       CortexStepType = 41
	CortexStepType_CORTEX_STEP_TYPE_TRAJECTORY_CHOICE      CortexStepType = 42
	CortexStepType_CORTEX_STEP_TYPE_PROXY_WEB_SERVER       CortexStepType = 43
	CortexStepType_CORTEX_STEP_TYPE_DEPLOY_WEB_APP         CortexStepType = 44
	CortexStepType_CORTEX_STEP_TYPE_CLIPBOARD              CortexStepType = 45
	CortexStepType_CORTEX_STEP_TYPE_READ_DEPLOYMENT_CONFIG CortexStepType = 46
	// Deprecated: Marked as deprecated in exa/cortex_pb/cortex.proto.
	CortexStepType_CORTEX_STEP_TYPE_VIEW_FILE_OUTLINE        CortexStepType = 47
	CortexStepType_CORTEX_STEP_TYPE_CHECK_DEPLOY_STATUS      CortexStepType = 48
	CortexStepType_CORTEX_STEP_TYPE_POST_PR_REVIEW           CortexStepType = 49
	CortexStepType_CORTEX_STEP_TYPE_READ_KNOWLEDGE_BASE_ITEM CortexStepType = 50
	CortexStepType_CORTEX_STEP_TYPE_LIST_RESOURCES           CortexStepType = 51
	CortexStepType_CORTEX_STEP_TYPE_READ_RESOURCE            CortexStepType = 52
	CortexStepType_CORTEX_STEP_TYPE_LINT_DIFF                CortexStepType = 53
	CortexStepType_CORTEX_STEP_TYPE_FIND_ALL_REFERENCES      CortexStepType = 54
	CortexStepType_CORTEX_STEP_TYPE_BRAIN_UPDATE             CortexStepType = 55
	CortexStepType_CORTEX_STEP_TYPE_RUN_EXTENSION_CODE       CortexStepType = 57
	// Deprecated: Marked as deprecated in exa/cortex_pb/cortex.proto.
	CortexStepType_CORTEX_STEP_TYPE_ADD_ANNOTATION    CortexStepType = 58
	CortexStepType_CORTEX_STEP_TYPE_PROPOSAL_FEEDBACK CortexStepType = 59
	CortexStepType_CORTEX_STEP_TYPE_TRAJECTORY_SEARCH CortexStepType = 60
	CortexStepType_CORTEX_STEP_TYPE_READ_TERMINAL     CortexStepType = 65
	// Deprecated: Marked as deprecated in exa/cortex_pb/cortex.proto.
	CortexStepType_CORTEX_STEP_TYPE_GET_DOM_TREE CortexStepType = 68
	// Deprecated: Marked as deprecated in exa/cortex_pb/cortex.proto.
	CortexStepType_CORTEX_STEP_TYPE_ARTIFACT_SUMMARY                 CortexStepType = 71
	CortexStepType_CORTEX_STEP_TYPE_RESOLVE_TASK                     CortexStepType = 72
	CortexStepType_CORTEX_STEP_TYPE_TODO_LIST                        CortexStepType = 73
	CortexStepType_CORTEX_STEP_TYPE_BLOCKING                         CortexStepType = 74
	CortexStepType_CORTEX_STEP_TYPE_EXPLORE_RESPONSE                 CortexStepType = 80
	CortexStepType_CORTEX_STEP_TYPE_READ_NOTEBOOK                    CortexStepType = 82
	CortexStepType_CORTEX_STEP_TYPE_EDIT_NOTEBOOK                    CortexStepType = 83
	CortexStepType_CORTEX_STEP_TYPE_SUPERCOMPLETE_ACTIVE_DOC         CortexStepType = 86
	CortexStepType_CORTEX_STEP_TYPE_FIND_CODE_CONTEXT                CortexStepType = 87
	CortexStepType_CORTEX_STEP_TYPE_SUPERCOMPLETE_FEEDBACK           CortexStepType = 89
	CortexStepType_CORTEX_STEP_TYPE_LINT_FIX_MESSAGE                 CortexStepType = 90
	CortexStepType_CORTEX_STEP_TYPE_GREP_SEARCH_V2                   CortexStepType = 91
	CortexStepType_CORTEX_STEP_TYPE_UPSERT_CODEMAP                   CortexStepType = 92
	CortexStepType_CORTEX_STEP_TYPE_SUGGEST_CODEMAP                  CortexStepType = 93
	CortexStepType_CORTEX_STEP_TYPE_SMART_FRIEND                     CortexStepType = 94
	CortexStepType_CORTEX_STEP_TYPE_DO_TESTING                       CortexStepType = 95
	CortexStepType_CORTEX_STEP_TYPE_REPORT_BUGS                      CortexStepType = 97
	CortexStepType_CORTEX_STEP_TYPE_EXIT_PLAN_MODE                   CortexStepType = 99
	CortexStepType_CORTEX_STEP_TYPE_ASK_USER_QUESTION                CortexStepType = 100
	CortexStepType_CORTEX_STEP_TYPE_SKILL                            CortexStepType = 101
	CortexStepType_CORTEX_STEP_TYPE_SUPERCOMPLETE_EPHEMERAL_FEEDBACK CortexStepType = 102
	CortexStepType_CORTEX_STEP_TYPE_ARENA_TRAJECTORY_CONVERGE        CortexStepType = 103
	CortexStepType_CORTEX_STEP_TYPE_TASK_SUBAGENT                    CortexStepType = 104
	CortexStepType_CORTEX_STEP_TYPE_LIST_MEMORIES                    CortexStepType = 105
	CortexStepType_CORTEX_STEP_TYPE_AI_GATEWAY                       CortexStepType = 106
)

// Enum value maps for CortexStepType.
var (
	CortexStepType_name = map[int32]string{
		0:   "CORTEX_STEP_TYPE_UNSPECIFIED",
		1:   "CORTEX_STEP_TYPE_DUMMY",
		2:   "CORTEX_STEP_TYPE_FINISH",
		3:   "CORTEX_STEP_TYPE_PLAN_INPUT",
		4:   "CORTEX_STEP_TYPE_MQUERY",
		5:   "CORTEX_STEP_TYPE_CODE_ACTION",
		6:   "CORTEX_STEP_TYPE_GIT_COMMIT",
		7:   "CORTEX_STEP_TYPE_GREP_SEARCH",
		8:   "CORTEX_STEP_TYPE_VIEW_FILE",
		9:   "CORTEX_STEP_TYPE_LIST_DIRECTORY",
		10:  "CORTEX_STEP_TYPE_COMPILE",
		11:  "CORTEX_STEP_TYPE_INFORM",
		12:  "CORTEX_STEP_TYPE_FILE_BREAKDOWN",
		13:  "CORTEX_STEP_TYPE_VIEW_CODE_ITEM",
		14:  "CORTEX_STEP_TYPE_USER_INPUT",
		15:  "CORTEX_STEP_TYPE_PLANNER_RESPONSE",
		16:  "CORTEX_STEP_TYPE_WRITE_TO_FILE",
		17:  "CORTEX_STEP_TYPE_ERROR_MESSAGE",
		18:  "CORTEX_STEP_TYPE_CLUSTER_QUERY",
		19:  "CORTEX_STEP_TYPE_LIST_CLUSTERS",
		20:  "CORTEX_STEP_TYPE_INSPECT_CLUSTER",
		21:  "CORTEX_STEP_TYPE_RUN_COMMAND",
		22:  "CORTEX_STEP_TYPE_RELATED_FILES",
		23:  "CORTEX_STEP_TYPE_CHECKPOINT",
		24:  "CORTEX_STEP_TYPE_PROPOSE_CODE",
		25:  "CORTEX_STEP_TYPE_FIND",
		26:  "CORTEX_STEP_TYPE_SEARCH_KNOWLEDGE_BASE",
		27:  "CORTEX_STEP_TYPE_SUGGESTED_RESPONSES",
		28:  "CORTEX_STEP_TYPE_COMMAND_STATUS",
		29:  "CORTEX_STEP_TYPE_MEMORY",
		30:  "CORTEX_STEP_TYPE_LOOKUP_KNOWLEDGE_BASE",
		31:  "CORTEX_STEP_TYPE_READ_URL_CONTENT",
		32:  "CORTEX_STEP_TYPE_VIEW_CONTENT_CHUNK",
		33:  "CORTEX_STEP_TYPE_SEARCH_WEB",
		34:  "CORTEX_STEP_TYPE_RETRIEVE_MEMORY",
		35:  "CORTEX_STEP_TYPE_AUTO_CASCADE_BROADCAST",
		36:  "CORTEX_STEP_TYPE_CUSTOM_TOOL",
		37:  "CORTEX_STEP_TYPE_CREATE_RECIPE",
		38:  "CORTEX_STEP_TYPE_MCP_TOOL",
		39:  "CORTEX_STEP_TYPE_MANAGER_FEEDBACK",
		40:  "CORTEX_STEP_TYPE_TOOL_CALL_PROPOSAL",
		41:  "CORTEX_STEP_TYPE_TOOL_CALL_CHOICE",
		42:  "CORTEX_STEP_TYPE_TRAJECTORY_CHOICE",
		43:  "CORTEX_STEP_TYPE_PROXY_WEB_SERVER",
		44:  "CORTEX_STEP_TYPE_DEPLOY_WEB_APP",
		45:  "CORTEX_STEP_TYPE_CLIPBOARD",
		46:  "CORTEX_STEP_TYPE_READ_DEPLOYMENT_CONFIG",
		47:  "CORTEX_STEP_TYPE_VIEW_FILE_OUTLINE",
		48:  "CORTEX_STEP_TYPE_CHECK_DEPLOY_STATUS",
		49:  "CORTEX_STEP_TYPE_POST_PR_REVIEW",
		50:  "CORTEX_STEP_TYPE_READ_KNOWLEDGE_BASE_ITEM",
		51:  "CORTEX_STEP_TYPE_LIST_RESOURCES",
		52:  "CORTEX_STEP_TYPE_READ_RESOURCE",
		53:  "CORTEX_STEP_TYPE_LINT_DIFF",
		54:  "CORTEX_STEP_TYPE_FIND_ALL_REFERENCES",
		55:  "CORTEX_STEP_TYPE_BRAIN_UPDATE",
		57:  "CORTEX_STEP_TYPE_RUN_EXTENSION_CODE",
		58:  "CORTEX_STEP_TYPE_ADD_ANNOTATION",
		59:  "CORTEX_STEP_TYPE_PROPOSAL_FEEDBACK",
		60:  "CORTEX_STEP_TYPE_TRAJECTORY_SEARCH",
		65:  "CORTEX_STEP_TYPE_READ_TERMINAL",
		68:  "CORTEX_STEP_TYPE_GET_DOM_TREE",
		71:  "CORTEX_STEP_TYPE_ARTIFACT_SUMMARY",
		72:  "CORTEX_STEP_TYPE_RESOLVE_TASK",
		73:  "CORTEX_STEP_TYPE_TODO_LIST",
		74:  "CORTEX_STEP_TYPE_BLOCKING",
		80:  "CORTEX_STEP_TYPE_EXPLORE_RESPONSE",
		82:  "CORTEX_STEP_TYPE_READ_NOTEBOOK",
		83:  "CORTEX_STEP_TYPE_EDIT_NOTEBOOK",
		86:  "CORTEX_STEP_TYPE_SUPERCOMPLETE_ACTIVE_DOC",
		87:  "CORTEX_STEP_TYPE_FIND_CODE_CONTEXT",
		89:  "CORTEX_STEP_TYPE_SUPERCOMPLETE_FEEDBACK",
		90:  "CORTEX_STEP_TYPE_LINT_FIX_MESSAGE",
		91:  "CORTEX_STEP_TYPE_GREP_SEARCH_V2",
		92:  "CORTEX_STEP_TYPE_UPSERT_CODEMAP",
		93:  "CORTEX_STEP_TYPE_SUGGEST_CODEMAP",
		94:  "CORTEX_STEP_TYPE_SMART_FRIEND",
		95:  "CORTEX_STEP_TYPE_DO_TESTING",
		97:  "CORTEX_STEP_TYPE_REPORT_BUGS",
		99:  "CORTEX_STEP_TYPE_EXIT_PLAN_MODE",
		100: "CORTEX_STEP_TYPE_ASK_USER_QUESTION",
		101: "CORTEX_STEP_TYPE_SKILL",
		102: "CORTEX_STEP_TYPE_SUPERCOMPLETE_EPHEMERAL_FEEDBACK",
		103: "CORTEX_STEP_TYPE_ARENA_TRAJECTORY_CONVERGE",
		104: "CORTEX_STEP_TYPE_TASK_SUBAGENT",
		105: "CORTEX_STEP_TYPE_LIST_MEMORIES",
		106: "CORTEX_STEP_TYPE_AI_GATEWAY",
	}
	CortexStepType_value = map[string]int32{
		"CORTEX_STEP_TYPE_UNSPECIFIED":                      0,
		"CORTEX_STEP_TYPE_DUMMY":                            1,
		"CORTEX_STEP_TYPE_FINISH":                           2,
		"CORTEX_STEP_TYPE_PLAN_INPUT":                       3,
		"CORTEX_STEP_TYPE_MQUERY":                           4,
		"CORTEX_STEP_TYPE_CODE_ACTION":                      5,
		"CORTEX_STEP_TYPE_GIT_COMMIT":                       6,
		"CORTEX_STEP_TYPE_GREP_SEARCH":                      7,
		"CORTEX_STEP_TYPE_VIEW_FILE":                        8,
		"CORTEX_STEP_TYPE_LIST_DIRECTORY":                   9,
		"CORTEX_STEP_TYPE_COMPILE":                          10,
		"CORTEX_STEP_TYPE_INFORM":                           11,
		"CORTEX_STEP_TYPE_FILE_BREAKDOWN":                   12,
		"CORTEX_STEP_TYPE_VIEW_CODE_ITEM":                   13,
		"CORTEX_STEP_TYPE_USER_INPUT":                       14,
		"CORTEX_STEP_TYPE_PLANNER_RESPONSE":                 15,
		"CORTEX_STEP_TYPE_WRITE_TO_FILE":                    16,
		"CORTEX_STEP_TYPE_ERROR_MESSAGE":                    17,
		"CORTEX_STEP_TYPE_CLUSTER_QUERY":                    18,
		"CORTEX_STEP_TYPE_LIST_CLUSTERS":                    19,
		"CORTEX_STEP_TYPE_INSPECT_CLUSTER":                  20,
		"CORTEX_STEP_TYPE_RUN_COMMAND":                      21,
		"CORTEX_STEP_TYPE_RELATED_FILES":                    22,
		"CORTEX_STEP_TYPE_CHECKPOINT":                       23,
		"CORTEX_STEP_TYPE_PROPOSE_CODE":                     24,
		"CORTEX_STEP_TYPE_FIND":                             25,
		"CORTEX_STEP_TYPE_SEARCH_KNOWLEDGE_BASE":            26,
		"CORTEX_STEP_TYPE_SUGGESTED_RESPONSES":              27,
		"CORTEX_STEP_TYPE_COMMAND_STATUS":                   28,
		"CORTEX_STEP_TYPE_MEMORY":                           29,
		"CORTEX_STEP_TYPE_LOOKUP_KNOWLEDGE_BASE":            30,
		"CORTEX_STEP_TYPE_READ_URL_CONTENT":                 31,
		"CORTEX_STEP_TYPE_VIEW_CONTENT_CHUNK":               32,
		"CORTEX_STEP_TYPE_SEARCH_WEB":                       33,
		"CORTEX_STEP_TYPE_RETRIEVE_MEMORY":                  34,
		"CORTEX_STEP_TYPE_AUTO_CASCADE_BROADCAST":           35,
		"CORTEX_STEP_TYPE_CUSTOM_TOOL":                      36,
		"CORTEX_STEP_TYPE_CREATE_RECIPE":                    37,
		"CORTEX_STEP_TYPE_MCP_TOOL":                         38,
		"CORTEX_STEP_TYPE_MANAGER_FEEDBACK":                 39,
		"CORTEX_STEP_TYPE_TOOL_CALL_PROPOSAL":               40,
		"CORTEX_STEP_TYPE_TOOL_CALL_CHOICE":                 41,
		"CORTEX_STEP_TYPE_TRAJECTORY_CHOICE":                42,
		"CORTEX_STEP_TYPE_PROXY_WEB_SERVER":                 43,
		"CORTEX_STEP_TYPE_DEPLOY_WEB_APP":                   44,
		"CORTEX_STEP_TYPE_CLIPBOARD":                        45,
		"CORTEX_STEP_TYPE_READ_DEPLOYMENT_CONFIG":           46,
		"CORTEX_STEP_TYPE_VIEW_FILE_OUTLINE":                47,
		"CORTEX_STEP_TYPE_CHECK_DEPLOY_STATUS":              48,
		"CORTEX_STEP_TYPE_POST_PR_REVIEW":                   49,
		"CORTEX_STEP_TYPE_READ_KNOWLEDGE_BASE_ITEM":         50,
		"CORTEX_STEP_TYPE_LIST_RESOURCES":                   51,
		"CORTEX_STEP_TYPE_READ_RESOURCE":                    52,
		"CORTEX_STEP_TYPE_LINT_DIFF":                        53,
		"CORTEX_STEP_TYPE_FIND_ALL_REFERENCES":              54,
		"CORTEX_STEP_TYPE_BRAIN_UPDATE":                     55,
		"CORTEX_STEP_TYPE_RUN_EXTENSION_CODE":               57,
		"CORTEX_STEP_TYPE_ADD_ANNOTATION":                   58,
		"CORTEX_STEP_TYPE_PROPOSAL_FEEDBACK":                59,
		"CORTEX_STEP_TYPE_TRAJECTORY_SEARCH":                60,
		"CORTEX_STEP_TYPE_READ_TERMINAL":                    65,
		"CORTEX_STEP_TYPE_GET_DOM_TREE":                     68,
		"CORTEX_STEP_TYPE_ARTIFACT_SUMMARY":                 71,
		"CORTEX_STEP_TYPE_RESOLVE_TASK":                     72,
		"CORTEX_STEP_TYPE_TODO_LIST":                        73,
		"CORTEX_STEP_TYPE_BLOCKING":                         74,
		"CORTEX_STEP_TYPE_EXPLORE_RESPONSE":                 80,
		"CORTEX_STEP_TYPE_READ_NOTEBOOK":                    82,
		"CORTEX_STEP_TYPE_EDIT_NOTEBOOK":                    83,
		"CORTEX_STEP_TYPE_SUPERCOMPLETE_ACTIVE_DOC":         86,
		"CORTEX_STEP_TYPE_FIND_CODE_CONTEXT":                87,
		"CORTEX_STEP_TYPE_SUPERCOMPLETE_FEEDBACK":           89,
		"CORTEX_STEP_TYPE_LINT_FIX_MESSAGE":                 90,
		"CORTEX_STEP_TYPE_GREP_SEARCH_V2":                   91,
		"CORTEX_STEP_TYPE_UPSERT_CODEMAP":                   92,
		"CORTEX_STEP_TYPE_SUGGEST_CODEMAP":                  93,
		"CORTEX_STEP_TYPE_SMART_FRIEND":                     94,
		"CORTEX_STEP_TYPE_DO_TESTING":                       95,
		"CORTEX_STEP_TYPE_REPORT_BUGS":                      97,
		"CORTEX_STEP_TYPE_EXIT_PLAN_MODE":                   99,
		"CORTEX_STEP_TYPE_ASK_USER_QUESTION":                100,
		"CORTEX_STEP_TYPE_SKILL":                            101,
		"CORTEX_STEP_TYPE_SUPERCOMPLETE_EPHEMERAL_FEEDBACK": 102,
		"CORTEX_STEP_TYPE_ARENA_TRAJECTORY_CONVERGE":        103,
		"CORTEX_STEP_TYPE_TASK_SUBAGENT":                    104,
		"CORTEX_STEP_TYPE_LIST_MEMORIES":                    105,
		"CORTEX_STEP_TYPE_AI_GATEWAY":                       106,
	}
)

func (x CortexStepType) Enum() *CortexStepType {
	p := new(CortexStepType)
	*p = x
	return p
}

func (x CortexStepType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CortexStepType) Descriptor() protoreflect.EnumDescriptor {
	return file_exa_cortex_pb_cortex_proto_enumTypes[1].Descriptor()
}

func (CortexStepType) Type() protoreflect.EnumType {
	return &file_exa_cortex_pb_cortex_proto_enumTypes[1]
}

func (x CortexStepType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CortexStepType.Descriptor instead.
func (CortexStepType) EnumDescriptor() ([]byte, []int) {
	return file_exa_cortex_pb_cortex_proto_rawDescGZIP(), []int{1}
}

type CortexTrajectoryReference struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TrajectoryId   string                 `protobuf:"bytes,1,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	TrajectoryType CortexTrajectoryType   `protobuf:"varint,3,opt,name=trajectory_type,json=trajectoryType,proto3,enum=exa.cortex_pb.CortexTrajectoryType" json:"trajectory_type,omitempty"`
	StepIndex      int32                  `protobuf:"varint,2,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`
	StepType       CortexStepType         `protobuf:"varint,4,opt,name=step_type,json=stepType,proto3,enum=exa.cortex_pb.CortexStepType" json:"step_type,omitempty"`
	ForceBillable  bool                   `protobuf:"varint,5,opt,name=force_billable,json=forceBillable,proto3" json:"force_billable,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CortexTrajectoryReference) Reset() {
	*x = CortexTrajectoryReference{}
	mi := &file_exa_cortex_pb_cortex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CortexTrajectoryReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CortexTrajectoryReference) ProtoMessage() {}

func (x *CortexTrajectoryReference) ProtoReflect() protoreflect.Message {
	mi := &file_exa_cortex_pb_cortex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CortexTrajectoryReference.ProtoReflect.Descriptor instead.
func (*CortexTrajectoryReference) Descriptor() ([]byte, []int) {
	return file_exa_cortex_pb_cortex_proto_rawDescGZIP(), []int{0}
}

func (x *CortexTrajectoryReference) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *CortexTrajectoryReference) GetTrajectoryType() CortexTrajectoryType {
	if x != nil {
		return x.TrajectoryType
	}
	return CortexTrajectoryType_CORTEX_TRAJECTORY_TYPE_UNSPECIFIED
}

func (x *CortexTrajectoryReference) GetStepIndex() int32 {
	if x != nil {
		return x.StepIndex
	}
	return 0
}

func (x *CortexTrajectoryReference) GetStepType() CortexStepType {
	if x != nil {
		return x.StepType
	}
	return CortexStepType_CORTEX_STEP_TYPE_UNSPECIFIED
}

func (x *CortexTrajectoryReference) GetForceBillable() bool {
	if x != nil {
		return x.ForceBillable
	}
	return false
}

var File_exa_cortex_pb_cortex_proto protoreflect.FileDescriptor

const file_exa_cortex_pb_cortex_proto_rawDesc = "" +
	"\n" +
	"\x1aexa/cortex_pb/cortex.proto\x12\rexa.cortex_pb\"\x90\x02\n" +
	"\x19CortexTrajectoryReference\x12#\n" +
	"\rtrajectory_id\x18\x01 \x01(\tR\ftrajectoryId\x12L\n" +
	"\x0ftrajectory_type\x18\x03 \x01(\x0e2#.exa.cortex_pb.CortexTrajectoryTypeR\x0etrajectoryType\x12\x1d\n" +
	"\n" +
	"step_index\x18\x02 \x01(\x05R\tstepIndex\x12:\n" +
	"\tstep_type\x18\x04 \x01(\x0e2\x1d.exa.cortex_pb.CortexStepTypeR\bstepType\x12%\n" +
	"\x0eforce_billable\x18\x05 \x01(\bR\rforceBillable*\xeb\a\n" +
	"\x14CortexTrajectoryType\x12&\n" +
	"\"CORTEX_TRAJECTORY_TYPE_UNSPECIFIED\x10\x00\x12(\n" +
	"$CORTEX_TRAJECTORY_TYPE_USER_MAINLINE\x10\x01\x12(\n" +
	"$CORTEX_TRAJECTORY_TYPE_USER_GRANULAR\x10\x02\x12(\n" +
	"$CORTEX_TRAJECTORY_TYPE_SUPERCOMPLETE\x10\x03\x12\"\n" +
	"\x1eCORTEX_TRAJECTORY_TYPE_CASCADE\x10\x04\x122\n" +
	"*CORTEX_TRAJECTORY_TYPE_BACKGROUND_RESEARCH\x10\x05\x1a\x02\b\x01\x12%\n" +
	"!CORTEX_TRAJECTORY_TYPE_CHECKPOINT\x10\x06\x12*\n" +
	"&CORTEX_TRAJECTORY_TYPE_RETRIEVE_MEMORY\x10\a\x12&\n" +
	"\"CORTEX_TRAJECTORY_TYPE_CUSTOM_TOOL\x10\b\x12'\n" +
	"#CORTEX_TRAJECTORY_TYPE_AUTO_CASCADE\x10\t\x12/\n" +
	"+CORTEX_TRAJECTORY_TYPE_AUTO_CASCADE_MANAGER\x10\n" +
	"\x12\"\n" +
	"\x1eCORTEX_TRAJECTORY_TYPE_APPLIER\x10\v\x12-\n" +
	")CORTEX_TRAJECTORY_TYPE_TOOL_CALL_PROPOSAL\x10\f\x12,\n" +
	"(CORTEX_TRAJECTORY_TYPE_TRAJECTORY_CHOICE\x10\r\x12$\n" +
	" CORTEX_TRAJECTORY_TYPE_LLM_JUDGE\x10\x0e\x12/\n" +
	"'CORTEX_TRAJECTORY_TYPE_ARTIFACT_SUMMARY\x10\x13\x1a\x02\b\x01\x12(\n" +
	"$CORTEX_TRAJECTORY_TYPE_PASSIVE_CODER\x10\x0f\x12.\n" +
	"*CORTEX_TRAJECTORY_TYPE_INTERACTIVE_CASCADE\x10\x11\x12'\n" +
	"#CORTEX_TRAJECTORY_TYPE_BRAIN_UPDATE\x10\x10\x12%\n" +
	"!CORTEX_TRAJECTORY_TYPE_AI_GATEWAY\x10\x16\"\x04\b\x12\x10\x12\"\x04\b\x14\x10\x14\"\x04\b\x15\x10\x15*!CORTEX_TRAJECTORY_TYPE_DEEP_THINK*'CORTEX_TRAJECTORY_TYPE_SUGGEST_CODE_MAP* CORTEX_TRAJECTORY_TYPE_LIFEGUARD*\xfb\x1c\n" +
	"\x0eCortexStepType\x12 \n" +
	"\x1cCORTEX_STEP_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CORTEX_STEP_TYPE_DUMMY\x10\x01\x12\x1b\n" +
	"\x17CORTEX_STEP_TYPE_FINISH\x10\x02\x12\x1f\n" +
	"\x1bCORTEX_STEP_TYPE_PLAN_INPUT\x10\x03\x12\x1b\n" +
	"\x17CORTEX_STEP_TYPE_MQUERY\x10\x04\x12 \n" +
	"\x1cCORTEX_STEP_TYPE_CODE_ACTION\x10\x05\x12\x1f\n" +
	"\x1bCORTEX_STEP_TYPE_GIT_COMMIT\x10\x06\x12 \n" +
	"\x1cCORTEX_STEP_TYPE_GREP_SEARCH\x10\a\x12\x1e\n" +
	"\x1aCORTEX_STEP_TYPE_VIEW_FILE\x10\b\x12#\n" +
	"\x1fCORTEX_STEP_TYPE_LIST_DIRECTORY\x10\t\x12\x1c\n" +
	"\x18CORTEX_STEP_TYPE_COMPILE\x10\n" +
	"\x12\x1b\n" +
	"\x17CORTEX_STEP_TYPE_INFORM\x10\v\x12'\n" +
	"\x1fCORTEX_STEP_TYPE_FILE_BREAKDOWN\x10\f\x1a\x02\b\x01\x12#\n" +
	"\x1fCORTEX_STEP_TYPE_VIEW_CODE_ITEM\x10\r\x12\x1f\n" +
	"\x1bCORTEX_STEP_TYPE_USER_INPUT\x10\x0e\x12%\n" +
	"!CORTEX_STEP_TYPE_PLANNER_RESPONSE\x10\x0f\x12&\n" +
	"\x1eCORTEX_STEP_TYPE_WRITE_TO_FILE\x10\x10\x1a\x02\b\x01\x12\"\n" +
	"\x1eCORTEX_STEP_TYPE_ERROR_MESSAGE\x10\x11\x12\"\n" +
	"\x1eCORTEX_STEP_TYPE_CLUSTER_QUERY\x10\x12\x12\"\n" +
	"\x1eCORTEX_STEP_TYPE_LIST_CLUSTERS\x10\x13\x12$\n" +
	" CORTEX_STEP_TYPE_INSPECT_CLUSTER\x10\x14\x12 \n" +
	"\x1cCORTEX_STEP_TYPE_RUN_COMMAND\x10\x15\x12\"\n" +
	"\x1eCORTEX_STEP_TYPE_RELATED_FILES\x10\x16\x12\x1f\n" +
	"\x1bCORTEX_STEP_TYPE_CHECKPOINT\x10\x17\x12!\n" +
	"\x1dCORTEX_STEP_TYPE_PROPOSE_CODE\x10\x18\x12\x19\n" +
	"\x15CORTEX_STEP_TYPE_FIND\x10\x19\x12.\n" +
	"&CORTEX_STEP_TYPE_SEARCH_KNOWLEDGE_BASE\x10\x1a\x1a\x02\b\x01\x12(\n" +
	"$CORTEX_STEP_TYPE_SUGGESTED_RESPONSES\x10\x1b\x12#\n" +
	"\x1fCORTEX_STEP_TYPE_COMMAND_STATUS\x10\x1c\x12\x1b\n" +
	"\x17CORTEX_STEP_TYPE_MEMORY\x10\x1d\x12.\n" +
	"&CORTEX_STEP_TYPE_LOOKUP_KNOWLEDGE_BASE\x10\x1e\x1a\x02\b\x01\x12%\n" +
	"!CORTEX_STEP_TYPE_READ_URL_CONTENT\x10\x1f\x12'\n" +
	"#CORTEX_STEP_TYPE_VIEW_CONTENT_CHUNK\x10 \x12\x1f\n" +
	"\x1bCORTEX_STEP_TYPE_SEARCH_WEB\x10!\x12$\n" +
	" CORTEX_STEP_TYPE_RETRIEVE_MEMORY\x10\"\x12+\n" +
	"'CORTEX_STEP_TYPE_AUTO_CASCADE_BROADCAST\x10#\x12 \n" +
	"\x1cCORTEX_STEP_TYPE_CUSTOM_TOOL\x10$\x12&\n" +
	"\x1eCORTEX_STEP_TYPE_CREATE_RECIPE\x10%\x1a\x02\b\x01\x12\x1d\n" +
	"\x19CORTEX_STEP_TYPE_MCP_TOOL\x10&\x12%\n" +
	"!CORTEX_STEP_TYPE_MANAGER_FEEDBACK\x10'\x12'\n" +
	"#CORTEX_STEP_TYPE_TOOL_CALL_PROPOSAL\x10(\x12%\n" +
	"!CORTEX_STEP_TYPE_TOOL_CALL_CHOICE\x10)\x12&\n" +
	"\"CORTEX_STEP_TYPE_TRAJECTORY_CHOICE\x10*\x12%\n" +
	"!CORTEX_STEP_TYPE_PROXY_WEB_SERVER\x10+\x12#\n" +
	"\x1fCORTEX_STEP_TYPE_DEPLOY_WEB_APP\x10,\x12\x1e\n" +
	"\x1aCORTEX_STEP_TYPE_CLIPBOARD\x10-\x12+\n" +
	"'CORTEX_STEP_TYPE_READ_DEPLOYMENT_CONFIG\x10.\x12*\n" +
	"\"CORTEX_STEP_TYPE_VIEW_FILE_OUTLINE\x10/\x1a\x02\b\x01\x12(\n" +
	"$CORTEX_STEP_TYPE_CHECK_DEPLOY_STATUS\x100\x12#\n" +
	"\x1fCORTEX_STEP_TYPE_POST_PR_REVIEW\x101\x12-\n" +
	")CORTEX_STEP_TYPE_READ_KNOWLEDGE_BASE_ITEM\x102\x12#\n" +
	"\x1fCORTEX_STEP_TYPE_LIST_RESOURCES\x103\x12\"\n" +
	"\x1eCORTEX_STEP_TYPE_READ_RESOURCE\x104\x12\x1e\n" +
	"\x1aCORTEX_STEP_TYPE_LINT_DIFF\x105\x12(\n" +
	"$CORTEX_STEP_TYPE_FIND_ALL_REFERENCES\x106\x12!\n" +
	"\x1dCORTEX_STEP_TYPE_BRAIN_UPDATE\x107\x12'\n" +
	"#CORTEX_STEP_TYPE_RUN_EXTENSION_CODE\x109\x12'\n" +
	"\x1fCORTEX_STEP_TYPE_ADD_ANNOTATION\x10:\x1a\x02\b\x01\x12&\n" +
	"\"CORTEX_STEP_TYPE_PROPOSAL_FEEDBACK\x10;\x12&\n" +
	"\"CORTEX_STEP_TYPE_TRAJECTORY_SEARCH\x10<\x12\"\n" +
	"\x1eCORTEX_STEP_TYPE_READ_TERMINAL\x10A\x12%\n" +
	"\x1dCORTEX_STEP_TYPE_GET_DOM_TREE\x10D\x1a\x02\b\x01\x12)\n" +
	"!CORTEX_STEP_TYPE_ARTIFACT_SUMMARY\x10G\x1a\x02\b\x01\x12!\n" +
	"\x1dCORTEX_STEP_TYPE_RESOLVE_TASK\x10H\x12\x1e\n" +
	"\x1aCORTEX_STEP_TYPE_TODO_LIST\x10I\x12\x1d\n" +
	"\x19CORTEX_STEP_TYPE_BLOCKING\x10J\x12%\n" +
	"!CORTEX_STEP_TYPE_EXPLORE_RESPONSE\x10P\x12\"\n" +
	"\x1eCORTEX_STEP_TYPE_READ_NOTEBOOK\x10R\x12\"\n" +
	"\x1eCORTEX_STEP_TYPE_EDIT_NOTEBOOK\x10S\x12-\n" +
	")CORTEX_STEP_TYPE_SUPERCOMPLETE_ACTIVE_DOC\x10V\x12&\n" +
	"\"CORTEX_STEP_TYPE_FIND_CODE_CONTEXT\x10W\x12+\n" +
	"'CORTEX_STEP_TYPE_SUPERCOMPLETE_FEEDBACK\x10Y\x12%\n" +
	"!CORTEX_STEP_TYPE_LINT_FIX_MESSAGE\x10Z\x12#\n" +
	"\x1fCORTEX_STEP_TYPE_GREP_SEARCH_V2\x10[\x12#\n" +
	"\x1fCORTEX_STEP_TYPE_UPSERT_CODEMAP\x10\\\x12$\n" +
	" CORTEX_STEP_TYPE_SUGGEST_CODEMAP\x10]\x12!\n" +
	"\x1dCORTEX_STEP_TYPE_SMART_FRIEND\x10^\x12\x1f\n" +
	"\x1bCORTEX_STEP_TYPE_DO_TESTING\x10_\x12 \n" +
	"\x1cCORTEX_STEP_TYPE_REPORT_BUGS\x10a\x12#\n" +
	"\x1fCORTEX_STEP_TYPE_EXIT_PLAN_MODE\x10c\x12&\n" +
	"\"CORTEX_STEP_TYPE_ASK_USER_QUESTION\x10d\x12\x1a\n" +
	"\x16CORTEX_STEP_TYPE_SKILL\x10e\x125\n" +
	"1CORTEX_STEP_TYPE_SUPERCOMPLETE_EPHEMERAL_FEEDBACK\x10f\x12.\n" +
	"*CORTEX_STEP_TYPE_ARENA_TRAJECTORY_CONVERGE\x10g\x12\"\n" +
	"\x1eCORTEX_STEP_TYPE_TASK_SUBAGENT\x10h\x12\"\n" +
	"\x1eCORTEX_STEP_TYPE_LIST_MEMORIES\x10i\x12\x1f\n" +
	"\x1bCORTEX_STEP_TYPE_AI_GATEWAY\x10j\"\x04\b8\x108\"\x04\b=\x10=\"\x04\b>\x10>\"\x04\b?\x10?\"\x04\b@\x10@\"\x04\bB\x10B\"\x04\bC\x10C\"\x04\bE\x10E\"\x04\bF\x10F\"\x04\bT\x10T\"\x04\bU\x10U\"\x04\bX\x10X\"\x04\b`\x10`\"\x04\bb\x10b\"\x04\bK\x10K\"\x04\bL\x10L\"\x04\bM\x10M\"\x04\bN\x10N\"\x04\bO\x10O\"\x04\bQ\x10Q*\x1bCORTEX_STEP_TYPE_DEEP_THINK*$CORTEX_STEP_TYPE_SUPERFLOW_SHOW_USER*\"CORTEX_STEP_TYPE_SUPERFLOW_CONTEXT*\"CORTEX_STEP_TYPE_CLAUDE_CODE_AGENT*&CORTEX_STEP_TYPE_CLAUDE_CODE_TODO_LIST*!CORTEX_STEP_TYPE_CLAUDE_CODE_GLOB*!CORTEX_STEP_TYPE_CLAUDE_CODE_DONE*#CORTEX_STEP_TYPE_CLAUDE_CODE_RESULT*,CORTEX_STEP_TYPE_CLAUDE_CODE_TOOL_PERMISSIONB2Z0github.com/Exafunction/Exafunction/exa/cortex_pbb\x06proto3"

var (
	file_exa_cortex_pb_cortex_proto_rawDescOnce sync.Once
	file_exa_cortex_pb_cortex_proto_rawDescData []byte
)

func file_exa_cortex_pb_cortex_proto_rawDescGZIP() []byte {
	file_exa_cortex_pb_cortex_proto_rawDescOnce.Do(func() {
		file_exa_cortex_pb_cortex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exa_cortex_pb_cortex_proto_rawDesc), len(file_exa_cortex_pb_cortex_proto_rawDesc)))
	})
	return file_exa_cortex_pb_cortex_proto_rawDescData
}

var file_exa_cortex_pb_cortex_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_exa_cortex_pb_cortex_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_exa_cortex_pb_cortex_proto_goTypes = []any{
	(CortexTrajectoryType)(0),         // 0: exa.cortex_pb.CortexTrajectoryType
	(CortexStepType)(0),               // 1: exa.cortex_pb.CortexStepType
	(*CortexTrajectoryReference)(nil), // 2: exa.cortex_pb.CortexTrajectoryReference
}
var file_exa_cortex_pb_cortex_proto_depIdxs = []int32{
	0, // 0: exa.cortex_pb.CortexTrajectoryReference.trajectory_type:type_name -> exa.cortex_pb.CortexTrajectoryType
	1, // 1: exa.cortex_pb.CortexTrajectoryReference.step_type:type_name -> exa.cortex_pb.CortexStepType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_exa_cortex_pb_cortex_proto_init() }
func file_exa_cortex_pb_cortex_proto_init() {
	if File_exa_cortex_pb_cortex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exa_cortex_pb_cortex_proto_rawDesc), len(file_exa_cortex_pb_cortex_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exa_cortex_pb_cortex_proto_goTypes,
		DependencyIndexes: file_exa_cortex_pb_cortex_proto_depIdxs,
		EnumInfos:         file_exa_cortex_pb_cortex_proto_enumTypes,
		MessageInfos:      file_exa_cortex_pb_cortex_proto_msgTypes,
	}.Build()
	File_exa_cortex_pb_cortex_proto = out.File
	file_exa_cortex_pb_cortex_proto_goTypes = nil
	file_exa_cortex_pb_cortex_proto_depIdxs = nil
}
